### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by JamesHarker** [attr-encrypted/attr_encrypted#101]
Does the project have a changelog? If not, are there any thoughts on adding one?

It would be super useful as currently I'm [manually diff-ing](https://github.com/attr-encrypted/attr_encrypted/compare/1.3.1...1.3.2) releases to find out what changed.

**Comment by saghaulor** [comment]
This was implemented starting at 7cafd38fdb809e3233c73e1effc3d2fa6a61f4cc
