### ISSUE TITLE
AR select  on an encrypted field

### ISSUE THREAD

**Issue by sopwithpup** [attr-encrypted/attr_encrypted#106]
I'd like to be able to do Table.select(:field) where field is in fact :encrypted_field but can't.

Also can't do Table.group(:name)

THis is rails4 ruby2 btw.

Am I missing something obv or can I just not to this?

TIA

**Comment by saghaulor** [comment]
@sopwithpup is the problem that you can't select a column, or that the values of the column are not decrypted when you select the column? Because the latter is a limitation of encrypting at the attribute, the former would most certainly be a bug.

**Comment by sopwithpup** [comment]
It's the latter, I've worked around it now, forgot about this issue (revisits dusty code just to check.....)
