### ISSUE TITLE
How to re-encrypt?

### ISSUE THREAD

**Issue by lewang** [attr-encrypted/attr_encrypted#109]
I've inherited a project where attr-encrypted is used.  If I need to change encryption keys OR algorithm, how do I do that?

IOW, I need to write a migration that decrypts using the current key/algo and re-encrypt using the new.  There does not appear an API beneath the magical layer that allows for this?

**Comment by barrywark** [comment]
It might be easier to use a blue/green approach. If you can spare the database columns, having two encrypted attributes (`password_blue` and `password_green`, for example), would allow you to migrate between the columns, using a separate key for each. At the app level, you could keep state variable that stores the current column (`blue` or `green`). Models would select the appropriate column based on state. Key rotation is then just copying the values from one column to the other (assuming both columns' keys are set) and then clearing the old value.

**Comment by abglassman** [comment]
An approach like [this one](https://cryptography.io/en/latest/fernet/#cryptography.fernet.MultiFernet) from the `Fernet` library in python might work: provide a list of configurations (a list of option maps, for example, or an option `legacy_options: [{algorithm: 'blahblah256`, key: 'oldkey'...},{...},...{...}]` - all encryption could be performed with the current set of options, decryption could be performed by trying the legacy configurations in sequence until something decrypts to a value that validates.

**Comment by saghaulor** [comment]
@lewang I don't know if you ever figured out how to achieve this, but work done in v3 makes this much easier. Re-encryption involves taking advantage of options evaluation at the instance level. https://github.com/attr-encrypted/attr_encrypted#options-are-evaluated

Essentially you'll create a class with functions that switch the options when decrypting and when encrypting. Then you'll cycle through your records with that class and migrate everything to the new implementation.

```ruby
class MigrateUserCrypto < ActiveRecord::Base
  self.table_name('users')

  attr_encrypted :ssn, key: key_toggle(:ssn), mode: mode_toggle(:ssn), algorithm: algorithm_toggle(:ssn), insecure_mode: is_decrypting?(:ssn)

  def is_decrypting?(attribute)
    encrypted_attributes[attribute][:operation] == :decrypting
  end

  def mode_toggle(attribute)
    if is_decrypting?(attribute)
      :single_iv_and_salt
    else
      :per_attribute_iv
    end
  end

  def algorithm_toggle(attribute)
    if is_decrypting?(attribute)
      'aes-256-cbc'
    else
      'aes-256-gcm'
    end
  end

  def key_toggle(attribute)
    if is_decrypting?(attribute)
      old_encryption_key
    else
      new_encryption_key
    end
  end
end

MigrateUserCrypto.all.each do |user|
  old_ssn = user.ssn
  user.ssn= old_ssn
  user.save
end
```

**Comment by hale** [comment]
FWIW I had to use `proc` as well, and the table name config is now a setter: `self.table_name = "users"`

This is in Rails 4 - maybe the code above is for Rails 3?

**Comment by rakibulislam** [comment]
@saghaulor I am following your example to create an instance method to toggle the key. Here is my code:
```ruby
class MigrateAccountCrypto < ActiveRecord::Base
  self.table_name = 'accounts'

  attr_encrypted :login, key: key_toggle(:login)
  attr_encrypted :password, key: key_toggle(:password)

  def is_decrypting?(attribute)
    encrypted_attributes[attribute][:operation] == :decrypting
  end

  def key_toggle(attribute)
    if is_decrypting?(attribute)
      Rails.application.secrets.attr_encrypted_key
    else
      Rails.application.secrets.new_attr_encrypted_key
    end
  end
end
```

But, I am getting this error:
```ruby
NoMethodError: undefined method `key_toggle' for #<Class:0x007fdeb2d055c8>
```
meaning that the instance method `key_toggle` as an option for `attr_encrypted :attribute` is not really working. I am using `attr_encrypted-3.0.3`. Is there anything that I am missing or I can try to make it work?

Thanks!

**Comment by saghaulor** [comment]
@rakibulislam I believe the way you're passing in the key_toggle method, the key_toggle is actually being called when the class is loading. I could be wrong.

Perhaps try this:
```ruby
 attr_encrypted :login, key: :key_toggle(:login)
 attr_encrypted :password, key: :key_toggle(:password)
```

**Comment by rakibulislam** [comment]
@saghaulor Thanks a lot for getting back to me. 
Actually `key: :key_toggle(:login)` is not a valid syntax, so I tried this way:
```ruby
  attr_encrypted :login, key: send(:key_toggle, :login)
  attr_encrypted :password, key: send(:key_toggle, :password)
```
But, still getting the same error:
```
rake aborted!
NoMethodError: undefined method `key_toggle' for #<Class:0x007fc83b0106c0>
```
It only works if the `key_toggle` method has no argument:
```ruby
attr_encrypted :login, key: :key_toggle
```
But, I need to send the attribute as the argument of the `key_toggle(:attribute)` method like you showed in your example above. Any thought?

**Comment by saghaulor** [comment]
@rakibulislam sorry about that, I thought that it might be invalid syntax.

You could always pass it as a proc.

```ruby
  attr_encrypted :login, key: Proc.new { |account| account.key_toggle( :login) }
  attr_encrypted :password, key: Proc.new { |account| account.key_toggle(:password) }
```

Hopefully that does what you need.

**Comment by rakibulislam** [comment]
@saghaulor awesome! That works perfectly :-) Thanks a bunch for the help 💯 ✋
