### ISSUE TITLE
Per-attribute salt and IV configuration is not documented

### ISSUE THREAD

**Issue by rcook** [attr-encrypted/attr_encrypted#118]
See https://github.com/attr-encrypted/attr_encrypted/issues/32#issuecomment-45797803 for discussion.

When I merged this functionality into this project, I neglected to bring the documentation in too. Please feel free to assign this bug to me and I'll take care of it.

**Comment by jancel** [comment]
@saghaulor, @rcook ; I'm doing some volunteer work for a company that wants to meet hipaa or pci (both are similar) encryption levels. I see @saghaulor code and I like this idea; but I'm not sure if any of you know whether I need to go this far. Also, are the column types still strings?  Did/have these methods (iv/salt) passed audit's (official or rigorous internal)?
