### ISSUE TITLE
question: decrypting columns in custom select statements select()

### ISSUE THREAD

**Issue by tony-kerz** [attr-encrypted/attr_encrypted#124]
my app has a series of custom queries crafted using active-record methods such as `join()` and `select()`. 

do you have any recommended strategy for decrypting encrypted fields during the response flow?

**Comment by swaps19** [comment]
thanks @tony-kerz it worked.. :+1: 
>my_field = object[:encrypted_my_field]
>puts "encrypted: my_field=[#{my_field}]"
>puts "decrypted: my_field=[#{MyModel.decrypt_my_field(my_field)}]"

but @billymonk while i was trying
`Person.decrypt_social_security_number(encrypted_social_security_number)`
this method, I got an exception of `wrong final block` .
I am curious why would it happen?
(I am a newbie to the rails)

**Comment by billymonk** [comment]
Hi @swaps19,

Welcome to the Rail's community! I haven't looked at the gem recently and am two jobs removed from using it daily but I'll try to take a look tonight so I can answer your question.

**Comment by mmahalwy** [comment]
How can I implement something like this with a service like elasticsearch?

**Comment by saghaulor** [comment]
@mmahalwy if you want to be able to search or index your sensitive data, you shouldn't use attr_enrypted or any solution that encrypts before the persistence layer. And I would ask you, is elasticsearch going to leak any of your sensitive data? If so is elasticsearch going to be encrypted? When you encrypt at the attribute level, you forgo functionality like searching, indexing, and joining on that data.
