### ISSUE TITLE
AR's reload method doesn't clear cached copy of decrypted data

### ISSUE THREAD

**Issue by seandilda** [attr-encrypted/attr_encrypted#127]
If I have a AR object in memory and edit the record in another process, I should be able to call #reload on the object to update its values.  This works for the values in the db.  However, attr-encrypted keeps a copy of the decrypted field cached and this isn't cleared, thus leading to unexpected behavior.

**Comment by rajaaa92** [comment]
+1

**Comment by billymonk** [comment]
@seandilda This is actually fixed in master. Try it out and if it looks good I'll cut a new version of the gem.
