### ISSUE TITLE
Salt uses only hex digits

### ISSUE THREAD

**Issue by pauljm** [attr-encrypted/attr_encrypted#133]
Rather than generating random bytes of salt and hex- (or base64-) encoding them in the database, the hex digits themselves are used as salt. This significantly decreases the entropy of the salt (16^16 = 1.8x10^19 instead of 256^16 = 3.4x10^38). Instead, like the IV, salt should be 16 completely random bytes that are base64-encoded in the database.

**Comment by saghaulor** [comment]
@pauljm please correct me if I'm wrong; I understand the issue that you have raised to be that the key space for hex is smaller than when using random bytes. Moreover, you're suggesting to use random bytes that are base64 encoded in the db but decoded before usage as salt.

**Comment by saghaulor** [comment]
@pauljm After doing a little more research I understand your concern. Last night I Implemented an improvement to use SecureRandom.hex instead of our current collision prone implementation. However, I agree that we should further improve the key space by using random bytes. As such I'll work on a solution. Thank you for raising this issue.

**Comment by pauljm** [comment]
Thanks for the update. I don't think the old salting strategy was any more collision-prone than SecureRandom, but at least the latter is clearer code. Would love to see more entropy in the salt, but 16 chars of hex may practically be plenty to prevent rainbow table attacks. I'll let the crypto experts do the math there.

**Comment by modosc** [comment]
(disclaimer: i'm not a crypto expert)

the old method was prone to collisions if you were inserting multiple values at the same time. as far as i can tell you were guaranteed a collision if you managed to create 1001 records inside of 1 second.
