### ISSUE TITLE
pluck-like functionality?

### ISSUE THREAD

**Issue by visibletrap** [attr-encrypted/attr_encrypted#134]
Is it a good idea to implement [pluck](http://api.rubyonrails.org/classes/ActiveRecord/Calculations.html#method-i-pluck)-like functionlity for **attr_encrypted**? Maybe for the first pass supporting only `model.pluck(:attr)` and `model.pluck(:attr1, :attr2, ...)`

I haven't really dig into attr_encrypted's source code to see if there's a possibility to implement it. But if you guys think it's good to have, I'll try to come up with something.

**Comment by saghaulor** [comment]
@visibletrap Are you asking about a pluck that does both pluck and decrypt? Or simply pluck?

**Comment by visibletrap** [comment]
I meant pluck and decrypt. There was a scenario where I want data only from an encrypted column not the whole record.

I don't want this functionality at the moment, sorry for forgetting to close the issue.

**Comment by dowi** [comment]
+1 i would love this functionality
