### ISSUE TITLE
Crash with AR uniqueness validator

### ISSUE THREAD

**Issue by Solher** [attr-encrypted/attr_encrypted#138]
Hi,

I'm currently trying to encrypt my user emails with attr_encrypted.
I renamed my column from "email" to "encrypted_email" and added "attr_encrypted :email, :key => 'key'" in my AR model.
When I try to create a new user, I get the following error.
When I deactivate my uniqueness validator, I don't get it anymore.

NoMethodError: undefined method `limit' for nil:NilClass
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activerecord-4.2.0.beta2/lib/active_record/validations/uniqueness.rb:64:in `build_relation'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activerecord-4.2.0.beta2/lib/active_record/validations/uniqueness.rb:18:in `validate_each'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activemodel-4.2.0.beta2/lib/active_model/validator.rb:151:in `block in validate'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activemodel-4.2.0.beta2/lib/active_model/validator.rb:148:in `each'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activemodel-4.2.0.beta2/lib/active_model/validator.rb:148:in `validate'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0.beta2/lib/active_support/callbacks.rb:447:in `public_send'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0.beta2/lib/active_support/callbacks.rb:447:in `block in make_lambda'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0.beta2/lib/active_support/callbacks.rb:186:in `call'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0.beta2/lib/active_support/callbacks.rb:186:in `block in simple'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0.beta2/lib/active_support/callbacks.rb:187:in `call'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0.beta2/lib/active_support/callbacks.rb:187:in `block in simple'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0.beta2/lib/active_support/callbacks.rb:87:in `call'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0.beta2/lib/active_support/callbacks.rb:87:in `run_callbacks'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activemodel-4.2.0.beta2/lib/active_model/validations.rb:393:in `run_validations!'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activemodel-4.2.0.beta2/lib/active_model/validations/callbacks.rb:111:in `block in run_validations!'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0.beta2/lib/active_support/callbacks.rb:83:in `run_callbacks'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activemodel-4.2.0.beta2/lib/active_model/validations/callbacks.rb:111:in `run_validations!'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activemodel-4.2.0.beta2/lib/active_model/validations.rb:332:in `valid?'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activerecord-4.2.0.beta2/lib/active_record/validations.rb:57:in `valid?'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activerecord-4.2.0.beta2/lib/active_record/validations.rb:82:in `perform_validations'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activerecord-4.2.0.beta2/lib/active_record/validations.rb:36:in `save'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activerecord-4.2.0.beta2/lib/active_record/attribute_methods/dirty.rb:21:in `save'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activerecord-4.2.0.beta2/lib/active_record/transactions.rb:284:in `block (2 levels) in save'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activerecord-4.2.0.beta2/lib/active_record/transactions.rb:345:in `block in with_transaction_returning_status'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activerecord-4.2.0.beta2/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activerecord-4.2.0.beta2/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activerecord-4.2.0.beta2/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activerecord-4.2.0.beta2/lib/active_record/transactions.rb:218:in `transaction'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activerecord-4.2.0.beta2/lib/active_record/transactions.rb:342:in `with_transaction_returning_status'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activerecord-4.2.0.beta2/lib/active_record/transactions.rb:284:in `block in save'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activerecord-4.2.0.beta2/lib/active_record/transactions.rb:299:in `rollback_active_record_state!'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activerecord-4.2.0.beta2/lib/active_record/transactions.rb:283:in `save'
/Volumes/Data/Users/Solher/.rvm/gems/ruby-2.1.3/gems/activerecord-4.2.0.beta2/lib/active_record/persistence.rb:34:in `create'

Do you have any idea where the problem could come from ?
Thanks

**Comment by saghaulor** [comment]
@Solher are you trying to use the uniqueness validation on the encrypted attribute? I believe this may be a futile effort since in order to check uniqueness the db would query all rows looking for a matching value of the current attribute value. However, since all data for that column would be cipher text, it would never find a match, which is to say, it would always be unique. Which is a long way of saying, why bother with uniqueness validation at all?

**Comment by Solher** [comment]
Of course, I'm not trying to check the uniqueness of the cipher text but the uniqueness of the email address.
I'd like to check if the email address the user want to sign up with is already taken or not.

**Comment by saghaulor** [comment]
@Solher Are you using per attribute salt and IV or single salt and IV?

**Comment by ryanh** [comment]
I am getting this exact error as well, and am using a per attribute salt and IV.

**Comment by saghaulor** [comment]
@ryanh using per_attribute_iv_and_salt mode it is effectively impossible to validate uniqueness. Please consider that to do so you would have to read out the salt and IV on every record, encrypt the new attribute with each salt and IV, and then search the entire table to verify that no record matching exists.

You can't validate uniqueness on encrypted records using per_attribute_iv_and_salt mode. It may be possible to do so using single_iv_and_salt mode, but you are then compromising the security of the data.

**Comment by duffyjp** [comment]
I need to validate uniqueness of an encrypted column (with per_attribute_iv) and came up with the following solution, I'd love to hear your take on it @saghaulor 

```
validate { errors.add(:ssn, 'has already been taken') if ssn.present? && ssn_changed? && Person.where.not(id: id, encrypted_ssn: nil).map(&:ssn).include?(ssn) }
```

It takes around 200ms to validate against our ~ 8000 row table, and only checks if the SSN is dirty.

**Comment by saghaulor** [comment]
Hello @duffyjp,

If you're using :per_attribute_iv, every record should have a unique IV, which means you'd have to cycle through every single IV, encrypt the record using each IV, then check to see if it matches any of the existing ciphertext.

Or you could decrypt every SSN, then match the decrypted values. Either way, it's not a very efficient process. With a small dataset it's feasible, but with an substantial dataset it's going to be painfully slow.

I assume the reason you're checking for uniqueness on SSN is that you don't trust user input. If it's some other reason, I'd be curious to know. Perhaps there's another more feasible solution.

**Comment by duffyjp** [comment]
I'm taking advantage of your helper methods, so I believe my above code is taking the decrypt everything approach.

In my situation I'm importing data from multiple external databases and need to ensure I don't duplicate my Person records.  I can tolerate a 200ms delay on creating new records, but obviously this doesn't scale for projects with say a million records.  Once the SSN is in the database there's no reason for it to change, so the validation shouldn't be even running very often.  

Along the same lines I had to implement a find_by_ssn method to look people up:

```ruby
  def self.find_by_ssn(ssn)
    all.each do |person|
      return person if person.ssn == ssn
    end
    nil # didn't find it
  end
```
Here the 200ms is worst case, if you're looking up literally the last person in the DB.  Average of 100ms then is pretty decent.  To be honest I'm shocked it's as fast as it is.

**Comment by rchekaluk** [comment]
Public service announcement: people needing to find a record by an encrypted attribute may be able to benefit from gem [blind_index](https://github.com/ankane/blind_index).
