### ISSUE TITLE
Question: Set universal key for entire application

### ISSUE THREAD

**Issue by coderhs** [attr-encrypted/attr_encrypted#149]
Hey there,

Just a question not an issue. Can we set a single key to be loaded from the secrets.yml during initialization of the rails application, so that we don't have to set they along with each attr_encrypted statement.

**Comment by billymonk** [comment]
Hi @coderhs,

The gem doesn't currently have that ability but I've marked this issue as an enhancement because I believe it would be nice to have.

Thanks

**Comment by Dschee** [comment]
+1

**Comment by carlosbutler** [comment]
Perhaps look at: https://mikecoutermarsh.com/rails-keeping-your-users-data-safe/, specifically the concern creation.

**Comment by jspanjers** [comment]
Would it be a good idea to set the key by default to Rails.application.secrets.secret_key_base ?

**Comment by saghaulor** [comment]
If you're ever going to rotate your data encryption key, which I highly advise you do, you'll want to keep some metadata with your records regarding which key was used to encrypt your record. That way, rotation and re-keying your data is much easier. Depending on the amount of encrypted data you use, re-keying may not be practical. So you'll leave old records encrypted with an old key, and encrypt new records with your new key. As such, having a mechanism that only allows for one key for the entire application may not be conducive to that end.

**Comment by saghaulor** [comment]
This is the same issue as #206 and will not be implemented as it encourages bad key management practices.
