### ISSUE TITLE
Why does the gem need to extend Object? This is a smell.

### ISSUE THREAD

**Issue by dzajic** [attr-encrypted/attr_encrypted#151]
I plan to answer my own question, but I'm throwing this out there in case someone already knows the answer and/or is interested in this question.

**Comment by mmclead** [comment]
It doesn't need to.  See Active Record's [store_accessor] (https://github.com/rails/rails/blob/master/activerecord/lib/active_record/store.rb) for how to def a new module, re-eval it upon each call of attr_encrypted and then insert the module.   This keeps it confined to the specific class and allows for normal method hierarchies to work.

**Comment by saghaulor** [comment]
I haven't used Datamapper or Sequel, but from my understanding of them, Models can be simple classes, namely, not inherited from the ORM. So if my understanding of attr_encrypted and Ruby is correct, the only way to include attr_encrypted behavior when using ORM adapters other than ActiveRecord is by extending Object.

**Comment by mmclead** [comment]
Fair point.  I have not looked at Datamapper or Sequel either so there could be something there.  

But the module approach will work for plain Ruby objects so it would seem like, without knowing about some specific reason, it would work for the other adapters as well.

**Comment by matt-glover** [comment]
Related: I would like to see the option to utilize this gem only on specific classes. The current implementation brings this library into every single object in your application. In my particular case I only need to encrypt/decrypt a small number of fields on a small number of classes. I would prefer the option to apply this functionality to those classes only.

i.e.
```ruby
class Foo
  extend AttrEncrypted
end

# Or perhaps for an ActiveRecord model
class Bar < ActiveRecord::Base
  extend AttrEncrypted::Adapters::ActiveRecord # or maybe `extend AttrEncrypted` could "magically" do the right thing
end
```

When the library extends Object the `attr_encrypted` gem shows up in the call chain in places you might not expect. I recently chased down a performance issue where this library was the primary culprit. The majority of CPU time was spent in `attr_encrypted`'s `method_missing` definition and methods called downstream from there. This happened even though the objects in question have no relationship to encryption/decryption.

**Comment by saghaulor** [comment]
This was fixed by https://github.com/attr-encrypted/attr_encrypted/pull/177

**Comment by dzajic** [comment]
Fantastic! Thanks, @saghaulor.
