### ISSUE TITLE
Please release a new version of gem 

### ISSUE THREAD

**Issue by randx** [attr-encrypted/attr_encrypted#155]
Fixes like this is very important - "ActiveRecord adapter no longer forces hashes to be string-keyed" 94d901df2ccbc579b981091d53dd641f9bed4c1d. 

I cant use the latest gem (Aug 2014) because it modifies behavior of application. If I add `attr_encrypted` to Gemfile -> `serialize` feature in AR start converting symbols into strings. Basically current released gem version (1.3.3) broke `serialize` feature of ActiveRecord

Thank you!

**Comment by dosire** [comment]
:+1: would be nice to have a new release

**Comment by dblessing** [comment]
:+1:

**Comment by saghaulor** [comment]
Hey guys, I plan on releasing a new version of the gem. However, as we've removed support for Ruby 1.8.7, we're going to be doing a major release. I am trying to put in any/all major changes before the new release. In the mean time I can try to push one last 1.x release that includes https://github.com/attr-encrypted/attr_encrypted/commit/94d901df2ccbc579b981091d53dd641f9bed4c1d

**Comment by randx** [comment]
@saghaulor It will be awesome if you can do last `1.3.x`. Mostly because there are gems with quite strict dependency on `attr_encrypted` like `devise-two-factor` - https://github.com/tinfoil/devise-two-factor/blob/master/devise-two-factor.gemspec#L30

**Comment by randx** [comment]
@saghaulor any chance I can help with patch release?

**Comment by randx** [comment]
Sorry for bothering but are there any news?

**Comment by saghaulor** [comment]
@randx sorry I've been out for a bit. I have started working on finishing up the last 1.x push. Stay tuned. Thank you for your patience.

**Comment by randx** [comment]
@saghaulor awesome! Thank you!

**Comment by DouweM** [comment]
@saghaulor How's the new version coming along?

**Comment by saghaulor** [comment]
@DouweM I was working on it last night. I'm trying to backport all the recent features applicable to Ruby 1.9.3. I've hit a snag with a failing test when I introduced the minitest changes. So I'm trying to get to the bottom of that. Thanks for your patience.

**Comment by DouweM** [comment]
@saghaulor Thank you!

**Comment by saghaulor** [comment]
@randx @DouweM @dosire @dblessing I've pushed v1.3.4.

**Comment by DouweM** [comment]
Thank you @saghaulor!

**Comment by randx** [comment]
@saghaulor Yay! Thank you a lot
