### ISSUE TITLE
find_by_email_and_password does not work, if one attribute is encrypted with salt and iv

### ISSUE THREAD

**Issue by cseydel** [attr-encrypted/attr_encrypted#161]
I use for password encryption ``per_attribute_iv_and_salt``
```
class Account < ActiveRecord::Base
  attr_encrypted :email,     key: ACCOUNT_ENCRYPTION_KEY
  attr_encrypted :password,  key: ACCOUNT_ENCRYPTION_KEY, mode: Proc.new { :per_attribute_iv_and_salt }
end
```

The query ``Account. find_by_email_and_password(EMAIL, PASSWORD)`` does return nil, because the password is not encrypted the same way.
Is there a mode to fix this?

**Comment by saghaulor** [comment]
@cseydel There is not. Moreover, the `find_by_*` feature relies on using an insecure more of encryption. I would advise that you reconsider your strategy.
