### ISSUE TITLE
Key length best practices?

### ISSUE THREAD

**Issue by D1plo1d** [attr-encrypted/attr_encrypted#165]
In the documentation it doesn't mention how long the key should be to be secure. Is there a best practice for the key length? Are there any issues with the underlying crypto where aes-256-cbc is known to be vulnerable to key lengths less then some threshold?

I just picked a really long key but it would be good to know.

**Comment by saghaulor** [comment]
@D1plo1d I believe when using AES-256-CBC, you should use a 256 bit/ 32 byte key. 

Please see http://www.cryptopp.com/wiki/Advanced_Encryption_Standard#Default_Key_Length
