### ISSUE TITLE
encrypted_column_name method \n at the end of encrypted password 

### ISSUE THREAD

**Issue by ganeshkumar** [attr-encrypted/attr_encrypted#167]
for example:
class User
  attr_accessor :name
  attr_encrypted :ssn, :key => 'a secret key'

  def load
    # loads the stored data
  end

  def save
    # saves the :name and :encrypted_ssn attributes somewhere (e.g. filesystem, database, etc)
  end
end

@user = User.new
@user.ssn = '123-45-6789'
@user.encrypted_ssn # returns the encrypted version of :ssn and it will be something like
"Wdjsgyhjeirek==\n"
The result should be "Wdjsgyhjeirek==" not "Wdjsgyhjeirek==\n"

**Comment by djohnson** [comment]
This is the expected behavior of the default encoding option: Array#pack('m') which encodes in Base64.

**Comment by saghaulor** [comment]
@ganeshkumar @djohnson is correct, this is standard behavior for base64 encoding.
