### ISSUE TITLE
Seems like mode is ignored?

### ISSUE THREAD

**Issue by flynfish** [attr-encrypted/attr_encrypted#168]
Using v 1.3.4..

We've tried both of these on the User model:
`attr_encrypted :ssn, :key => 'blahblah', :mode => :per_attribute_iv_and_salt`
`attr_encrypted :ssn, :key => 'blahblah', :mode => Proc.new { :per_attribute_iv_and_salt }`

When an ssn is updated on the user, the User record has new `encrypted_ssn_salt` and `encrypted_ssn_iv` values.

However, it seems like the single_attribute_iv_and_salt is still being used and a similar bug to https://github.com/attr-encrypted/attr_encrypted/issues/86 is happening ...

Last User has `ssn == 12345678` 
1. Start new rails console.
2. `irb> User.find_by_ssn('12345678') -> nil`
3. `irb> User.last -> gets last user`
4. `irb> User.find_by_ssn('12345678') -> get's last user`
5. `irb> User.first('12345678') -> get's first user`
6. `irb> User.find_by_ssn('12345678') -> nil`

**Comment by saghaulor** [comment]
@flynfish The dynamic `find_by_` methods are only supported when using the :single_iv_and_salt mode.
