### ISSUE TITLE
attr_encrypted and hstore

### ISSUE THREAD

**Issue by tigus** [attr-encrypted/attr_encrypted#169]
Hello, 

i got trouble with hstore and database (postgres)

attr_encrypted works perfectly fine for normal field.

but i have trouble to save something in a hstore 

````
 a.sort_code = 'foo'
=> "foo"
 a.encrypted_sort_code
=> "a0cOJLTqrF7SKWniAGIfOg==\n"
 a.save
   (0.1ms)  BEGIN
   (0.1ms)  COMMIT
=> true
```
 we can see all data are correct in object but when i try to save any update is made.


Do you have a idea to fixed that

tx for your nice gem

**Comment by tigus** [comment]
my fault i had declared attr_encrypted before my store_accessor then it s logical...

**Comment by sscirrus** [comment]
Please give more information on this - what code did you change to fix it?

**Comment by tigus** [comment]
Hello, 

I had made that before

```
attr_encrypted :sort_code, :key => xxx, :encode => true
store_accessor :more, [:sort_code, :bank_account]
```

but you have to respect good order

and write like that (declaration of store_accesor before the encrypted attr)

```
store_accessor :more, [:sort_code, :bank_account]
attr_encrypted :sort_code, :key => xxx, :encode => true
```

i hope that it could be help you

**Comment by sscirrus** [comment]
Thank you very much @tigus! This was helpful.

**Comment by rept** [comment]
I have this code:

    attr_encrypted :settings, key: 'XXXXXSXXHSHUXHXHXHIUSXHUSXHUSXSUHSX', marshal: true
    store_accessor :settings, :token, :organisation

I am able to get something like this:

    Integration.first.settings['access_key']

However when I try to do it like this:

    Integration.first.token

I get this error message:

    NoMethodError: undefined method `accessor' for #<ActiveRecord::Type::Value:0x007f8976ad4650>

This worked before.  Is it possible to use store_accessor's and still encrypt the complete column?

**Comment by tigus** [comment]
Try to put store_accessor before attr_encrypted...We never know...
But I'm not sure that you can encrypt a entire hstore in once ...

**Comment by mur-wtag** [comment]
Database migration looks like:
```ruby
...
      t.hstore :encrypted_credentials
      t.string :encrypted_credentials_salt
      t.string :encrypted_credentials_iv
...
```

I'm using STI, and models looks like

```ruby
# account.rb
class Account < ApplicationRecord
  attr_encrypted :credentials, key: Global.encryption.secure_encryption_key, marshal: true, allow_empty_value: false
end
```

And child class
```ruby
# account/acunt.rb

class Account::Acunt
    store_accessor :credentials, :merchant_account_id
    store_accessor :credentials, :secret_key

    validates :merchant_account_id, :secret_key, presence: true
    attr_encrypted :merchant_account_id, key: Global.encryption.secure_encryption_key, marshal: true, allow_empty_value: false
    attr_encrypted :secret_key, key: Global.encryption.secure_encryption_key, marshal: true, allow_empty_value: false
end
```

Yes, record is persisting successfully (using `Account::Acunt.create! merchant_account_id: 'some-id', secret_key: 'some-key'`), *BUT* without credentials!

No validation error, not noting but when try to retrieve data using something like `Account::Acunt.first.merchant_account_id` or `Account::Acunt.first.credentials` it's returns `nil`.

Any help would be appreciable.

**Comment by zoras** [comment]
> For anyone else stumbling on this issue, I managed to work around this by converting the column type from `hstore` to `jsonb` which seems to work pretty well.

ankane/kms_encrypted/issues/4
