### ISSUE TITLE
Adding fuzzy search examples to README

### ISSUE THREAD

**Issue by carlosbutler** [attr-encrypted/attr_encrypted#170]
Having looked around for fuzzy searching on encrypted columns, at the moment it's pretty difficult to do in MySQL (at least I could not find anything).

With Rails one could load required columns and using a rails select return the data required:

    User.select(:id, :encrypted_email).select{|t| t.email.include? 'part_of@email' }.map(&:id)

I've quickly experimented on this and for a list of ~2k users took ~4 seconds (I know, not quick...) to return the list of matching ID's. Perhaps you could add to the README better ways of fuzzy searches.

**Comment by swaps19** [comment]
i think this thread might help you..
#124

**Comment by saghaulor** [comment]
Please see my comments regarding searching encrypted data here https://github.com/attr-encrypted/attr_encrypted/issues/124#issuecomment-177691588
