### ISSUE TITLE
Rails in development -- getting 'bad decrypt'

### ISSUE THREAD

**Issue by b-d-b** [attr-encrypted/attr_encrypted#173]
Hey guys!  Great work with this gem, it's worked great for production, however I am having some issues in development now.

I have setup my secret key as a yml file in my config and setup my production and development environments to load the secret key as an environment variable.  My models are pulling the secret key from a concern class like so

from models/concerns/encryption.rb:
```
module Encryption
  extend ActiveSupport::Concern

  module ClassMethods
    def encryption_key
      # if in production. require key to be set.
      if Rails.env.production? || Rails.env.development?
        raise 'Must set token key!!' unless ENV['TOKEN_KEY']
        ENV['TOKEN_KEY']
      else
        ENV['TOKEN_KEY'] ? ENV['TOKEN_KEY'] : 'test_key'
      end
    end
  end

end
```

Then on my Devise user model:

```
class User < ActiveRecord::Base
  include Encryption
  attr_encrypted :first_name, :last_name, :middle_name, :email, :key => encryption_key
end
```

I have confirmed that the TOKEN_KEY env variable is correctly set in development and that the models are correctly getting those keys loaded.  However, when I go to do something like this:

```
User.first.first_name
```

I get the following error:

```
OpenSSL::Cipher::CipherError: bad decrypt
        from /Users/mike/.rvm/gems/ruby-2.1.2/gems/encryptor-1.3.0/lib/encryptor.rb:73:in `final'
        from /Users/mike/.rvm/gems/ruby-2.1.2/gems/encryptor-1.3.0/lib/encryptor.rb:73:in `crypt'
        from /Users/mike/.rvm/gems/ruby-2.1.2/gems/encryptor-1.3.0/lib/encryptor.rb:44:in `decrypt'
        from /Users/mike/.rvm/gems/ruby-2.1.2/gems/attr_encrypted-1.3.3/lib/attr_encrypted.rb:196:in `decrypt'
        from /Users/mike/.rvm/gems/ruby-2.1.2/gems/attr_encrypted-1.3.3/lib/attr_encrypted.rb:279:in `decrypt'
        from /Users/mike/.rvm/gems/ruby-2.1.2/gems/attr_encrypted-1.3.3/lib/attr_encrypted.rb:143:in `block (2 levels) in attr_encrypted'
        from (irb):1
        from /Users/mike/.rvm/gems/ruby-2.1.2/gems/railties-4.0.2/lib/rails/commands/console.rb:90:in `start'
        from /Users/mike/.rvm/gems/ruby-2.1.2/gems/railties-4.0.2/lib/rails/commands/console.rb:9:in `start'
        from /Users/mike/.rvm/gems/ruby-2.1.2/gems/railties-4.0.2/lib/rails/commands.rb:62:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'

```

However, when I run the same ```User.first.first_name``` in rails console in production environment, I do not get this error.

What am I doing wrong?

**Comment by faramund** [comment]
I had the same problem, but not in production. I changed encryption_key, but attributes in a database was encrypted with old encryption_key. 
My solution:
I set this attributes to NULL and filled with new values.

**Comment by a17levine** [comment]
Having the same problem and resetting the info hasn't helped as @faramund suggested. @b-d-b did you figure this one out? Here's what it looks like on my end, I wish I knew where to start debugging this but I don't even have a proper error here to go off of. I'm encrypting the 'email' field of user and it works fine in Rails Console but not in the browser apparently. Frustrating!

<img width="1258" alt="screen shot 2016-03-21 at 8 40 09 am" src="https://cloud.githubusercontent.com/assets/3523841/13918967/0405693e-ef41-11e5-8b7f-9aa34391c576.png">

**Comment by a17levine** [comment]
@b-d-b I figured out my problem. the code in `models/concerns/encryption.rb:` was giving me two different keys depending on whether I was in Rails Console or Rails Server which obviously would make the app choke on it

**Comment by saghaulor** [comment]
Please be sure to use the same key during decryption that was used during encryption. I recommend storing metadata about the key that was used to encrypt the ciphertext. That metadata can then be used to retrieve the correct key.
