### ISSUE TITLE
searching with external services

### ISSUE THREAD

**Issue by mmahalwy** [attr-encrypted/attr_encrypted#184]
Services like elasticsearch or algolia need to index the records. I want to index them encrypted and do a search on them, any idea or suggestions how this could be done?

**Comment by saghaulor** [comment]
@mmahalwy if you want to be able to search or index your sensitive data, you shouldn't use attr_enrypted or any solution that encrypts before the persistence layer. And I would ask you, is elasticsearch going to leak any of your sensitive data? If so is elasticsearch going to be encrypted? When you encrypt at the attribute level, you forgo functionality like searching, indexing, and joining on that data.

You have to make a decision based on your threat analysis, and your business needs. If you want to be able to search and index the data, perhaps you can use a db/table level encryption solution. If you want the data to be the most secure, you encrypt before persisting, but you forgo a lot of functionality.

**Comment by mmahalwy** [comment]
@saghaulor thanks for the detailed answer. Yes, seems like searching is not an option when encrypting in general.
