### ISSUE TITLE
Rails Admin searchable

### ISSUE THREAD

**Issue by kayzee** [attr-encrypted/attr_encrypted#186]
I'm using attr_enctyped to encrypt a number of fields in my model, including first_name, last_name in the Profile->User association.

I'd like to search the first_name field, but it doesn't exist in the database (encrypted_first_name does).

**Comment by saghaulor** [comment]
Searching is not possible when you encrypt at the record level as attr_encrypted does. If you could search it, it's not encrypted (or at least not very well). 

If you want to search those fields, consider using something at the table/database level, not at the row level (before it hits the persistence layer). 

Also keep in mind that your search tool will index your data, revealing your data, so your indexes need to be encrypted as well.

**Comment by kayzee** [comment]
Thanks for the feedback.  I was trying to search with RailsAdmin and it appears that it is using SQL to search the DB, which obviously won't work.

`...OR (LOWER(profiles.encrypted_first_name) LIKE '%kevin%')...`

**Comment by gerardo-navarro** [comment]
Is there a way to enable rails admin to do the search after it has fetched and decrypted the records from the database. I know it will be very very slow, but at least it might work?

**Comment by saghaulor** [comment]
@gerardo-navarro you could create a hash of the decrypted names. Depending on the number of names you're persisting, this may not be very practical. As you have already stated, this will be slow. You'll want to throw this away pretty quickly otherwise why are you even encrypting at rest?
