### ISSUE TITLE
`alias_method_chain` is deprecated

### ISSUE THREAD

**Issue by connorshea** [attr-encrypted/attr_encrypted#193]
I keep getting this deprecation warning with Ruby 2.3.0 and Rails 5:

```
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /Users/connor/.rvm/gems/ruby-2.3.0/bundler/gems/devise-two-factor-ba6c4c53efcc/lib/devise_two_factor/models/two_factor_authenticatable.rb:1)
```

Initially I thought this was an issue with devise_two_factor, but the line it refers to is `require 'attr_encrypted'`. Updating the gem to use attr_encrypted v2.0.0 doesn't fix this issue, unfortunately.

`alias_method_chain` is used throughout [this file](https://github.com/attr-encrypted/attr_encrypted/blob/master/lib/attr_encrypted/adapters/active_record.rb#L16).

Would it be possible to remove these from the gem? It's clogging up my terminal a bit :)

<img width="822" alt="screen shot 2016-02-25 at 12 35 53 pm" src="https://cloud.githubusercontent.com/assets/2977353/13331804/7129bc7e-dbbc-11e5-9c08-b07edca28137.png">

**Comment by connorshea** [comment]
Here's [the first relevant Rails Pull Request](https://github.com/rails/rails/pull/19434) and [the second](https://github.com/rails/rails/pull/19413) that deprecated `alias_method_chain`.

Deprecated by Rails 5.0.0, you can test it on the beta releases if need be.

**Comment by saghaulor** [comment]
Thanks for opening this issue @connorshea I am aware that `alias_method_chain` is deprecated in Rails 5. I intend to address this issue in a later release. However, you're welcome to open a pull request if you end up implementing the solution first.

**Comment by sblackstone** [comment]
# #213  Removes dependencies on alias_method_chain but does require that the version of ruby running supports prepend..

**Comment by dwickwire** [comment]
Version `3.0.1` still has the alias_method_chain so we just need a patch level bump to `3.0.2` to get the transition from `alias_method_chain` to `alias_method` [in May](https://github.com/attr-encrypted/attr_encrypted/commit/7dffc8607c6e096f2f497c9cf04e765ece89c2aa).  

In the meantime if you just want to upgrade to Rails 5 you can just point to github in your Gemfile:
```diff
- gem 'attr_encrypted', '3.0.1'
+ gem 'attr_encrypted', git: 'git://github.com/attr-encrypted/attr_encrypted.git'
```

**Comment by gylaz** [comment]
Any idea when a new version with the fix for this will be released?

**Comment by saghaulor** [comment]
I'll try to push a new release tonight. I was trying to kill a few more low hanging fruit issues before I pushed a new release.

**Comment by saghaulor** [comment]
Closed by #214

**Comment by connorshea** [comment]
@saghaulor thanks!

**Comment by saghaulor** [comment]
For those of you following this thread waiting for a gem push, I've hit a speed bump. The travis build for Rails 5 using Ruby 2.3 is failing. I need to investigate the failure. You're welcome to help.

When I get the build passing I'll push the new gem version.

**Comment by saghaulor** [comment]
Please see https://rubygems.org/gems/attr_encrypted/versions/3.0.2 for the new version.

**Comment by croaky** [comment]
Thank you!
