### ISSUE TITLE
Must specify an iv

### ISSUE THREAD

**Issue by chadwtaylor** [attr-encrypted/attr_encrypted#194]
We have been using this gem without issues (v1.3.4) and all of a sudden, it is breaking our code with the error: `must specify an iv`. It's affecting every records and we're stumped because there hasn't been any changes in that regard so I'm wondering if you have any insight into what is going on and what we can do to resolve this error?

Thanks in advance.

**Comment by Ewg777** [comment]
+1

**Comment by saghaulor** [comment]
Please upgrade to v1.3.5. Please see https://github.com/attr-encrypted/attr_encrypted/issues/181#issuecomment-171755632 for more details.

**Comment by chadwtaylor** [comment]
Wanted to confirm that upgrading to v1.3.5 fixed it, thanks.

**Comment by Ewg777** [comment]
@saghaulor https://github.com/attr-encrypted/attr_encrypted/blob/master/lib/attr_encrypted.rb#L136 is default_encoding okay here?

**Comment by saghaulor** [comment]
@Ewg777 I don't understand your question. Can you please clarify?

**Comment by Ewg777** [comment]
@saghaulor updated. 
Config 
```ruby
:encryption_key = 'test_some string 32-simbol-llength'
  attr_encrypted :city, :key => :encryption_key
```

**Comment by Ewg777** [comment]
@saghaulor should I store city_iv in the db as well?

**Comment by MattAttack07** [comment]
I recently upgraded from 1.3.5 to 2.0.0 and I am unable access the decrypted value, getting `must specify an iv`. 
```Model:
attr_encrypted :access_token, key: ENV['ACCESS_TOKEN']
```
Accessing `model.encrypted_access_token` shows the encrypted value, but trying to access `model.access_token` provides ```ArgumentError: must specify a key
from /usr/local/lib/ruby/gems/2.3.0/gems/encryptor-2.0.0/lib/encryptor.rb:54:in `crypt` ```

**Ruby 2.3.0** (rbenv)
**Rails 4.2.5.2**

I read through the README but I do not see anything has changed, that I can tell.

My apologies if this is the wrong place to put this issue.

**Comment by dyg2104MD** [comment]
+1 to MattAttack07's comment

**Comment by dyg2104MD** [comment]
thank you

**Comment by alokrawat050** [comment]
thanks @MattAttack07 
it helps me.

**Comment by dwickwire** [comment]
@saghaulor Any tips on migrating existing encrypted data from a `:single_iv_and_salt` over to `:per_attribute_iv`?

I have `:per_attribute_iv` set up and new records get a `<attribute>_iv` populated automatically during record creation, so I guess that's happening by way of either attr_encrytor or the encryptor gem.   If I however try to load a page which wants to display an older records which was previously encrypted by `:single_iv_and_salt`, I'll still get the "Must specify an iv".  Do you have any tips on how to "re-encrypt everything while your application is offline"?

One more comment: if I try to decrypt it with Encryptor alone, I'll get the same "Must specify an iv" error, with or without `:single_iv_and_salt` or `:per_attribute_iv`.

**Comment by saghaulor** [comment]
@dwickwire You need to pass the ```:insecure_mode``` option to Encryptor. Please see https://github.com/attr-encrypted/encryptor#options for more info.

**Comment by dwickwire** [comment]
Hm.  That still doesn't, I just get a cipererror, and I've tried all kinds of variations on this.
```
irb(main):003:0> Encryptor.decrypt(e.encrypted_data, key: <mykey>, insecure_mode: true)
OpenSSL::Cipher::CipherError: wrong final block length
```

Any tips on making the migration to the other mode?  From your answer I take it I'm on the right track but just need to get Encryptor to work?

**Comment by saghaulor** [comment]
@dwickwire Assuming you were using all of the default options from v1, try:

```ruby
Encryptor.decrypt(e.encrypted_data, key: <mykey>, insecure_mode: true, algorithm: 'aes-256-cbc', mode: :single_iv_and_salt)
```

**Comment by ibrahim-saifee** [comment]
This might help :slightly_smiling_face: 
The solution is really very strange. I am investigating it and will update soon on this.
https://github.com/attr-encrypted/attr_encrypted/issues/277#issuecomment-606516362
