### ISSUE TITLE
decryption error

### ISSUE THREAD

**Issue by interestinall** [attr-encrypted/attr_encrypted#195]
My attribute is being encrypted and saved in the db, but when I try to retrieve the decrypted value (user.first_name) I keep getting this error:

OpenSSL::Cipher::CipherError: 
from /Users/jl/.rvm/gems/ruby-2.1.7/gems/encryptor-2.0.0/lib/encryptor.rb:94:in `final'

here's the relevant code from my model:
```

attr_encrypted :first_name, key: :encryption_key, iv: :encryption_iv

 def encryption_key
    SecureRandom.random_bytes(32)
 end

 def encryption_iv
    SecureRandom.random_bytes(12)
 end
```

Anyone have an idea what the issue is?

**Comment by saghaulor** [comment]
@interestinall I suspect that your key and IV are are wrong. You're generating a new key and IV every time you call `encryption_key` and `encryption_iv`, which is to say, when you encryption you use one key and IV, and when you decrypt, you use a different key and IV.

Please review the README carefully for examples on how to correctly use attr_encrypted. Specifically, an IV per record will be generated for you. If you want a unique key per record you can use `:per_attribute_iv_and_salt` mode, or explore alternative mechanisms that are faster.
