### ISSUE TITLE
NotImplementedError (authenticated?() function is unimplemented on this machine

### ISSUE THREAD

**Issue by dnstevenson1** [attr-encrypted/attr_encrypted#199]
I am getting the following error when attempting to save a record:

"NotImplementedError (authenticated?() function is unimplemented on this machine"

Could someone point me in the right direction to correct this? My usual google-fu is coming up short.

My setup:

Rails 4.2.5
ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15] (Mac OS X 10.11.3)
attr_encrypted/encryptor 2.0

In my Rails ActiveRecord model the only option I pass besides the key is algorithm: 'aes-256-cfb'
(note: i've tried a few different 'aes-256-xxx' algorithms with the same effect)

**Comment by saghaulor** [comment]
The `authenticated` function is built into the OpenSSL standard library. http://ruby-doc.org/stdlib-2.0.0/libdoc/openssl/rdoc/OpenSSL/Cipher.html#method-i-authenticated-3F

Please be sure that you're specifying a supported algorithm: https://github.com/attr-encrypted/attr_encrypted#the-algorithm-option

**Comment by dnstevenson1** [comment]
Thanks for the response. I have followed the directions in the readme to check 'supported' algorithms. The output of OpenSSL::Cipher.ciphers lists several dozen, of which I've tried over 30 of them... all of which return the same NotImplmentedError. 

Is anyone else on OSX El Capitan and receiving similar errors? I only see this problem on my local OSX box.. our production *nix servers are fine.

**Comment by saghaulor** [comment]
Are you certain that you're using Ruby >= v2.0.0?

**Comment by dnstevenson1** [comment]
Yes:

ruby -v
ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
$ irb
irb(main):001:0> RUBY_VERSION
=> "2.0.0"
irb(main):002:0> require 'openssl'
=> true
irb(main):003:0> OpenSSL::Cipher.new("AES-256-CFB").authenticated?
NotImplementedError: authenticated?() function is unimplemented on this machine
	from (irb):3:in `authenticated?'
	from (irb):3
	from /usr/bin/irb:12:in `<main>'

**Comment by bluegod** [comment]
Just in case someone else has this issue, it looks like it has to do with the Ruby version not compiled with the OpenSSL extensions correctly. See what we found in https://gitlab.com/gitlab-org/gitlab-ce/issues/19218
