### ISSUE TITLE
Upgrading from 1.3.4 to 1.4.0 breaks existing applications

### ISSUE THREAD

**Issue by tilo** [attr-encrypted/attr_encrypted#201]
I think attr_encrypted should be more careful about not changing the default behavior of the encryption.

When I upgraded from 1.3.4 to 1.4.0 , I got this:

```
E, [2016-03-15T12:40:37.044311 #58] ERROR -- : Exception occured: OpenSSL::Cipher::CipherError - bad decrypt
E, [2016-03-15T12:40:37.044404 #58] ERROR -- : Exception backtrace:
E, [2016-03-15T12:40:37.044449 #58] ERROR -- : => /opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/encryptor-1.3.0/lib/encryptor.rb:73:in `final'
E, [2016-03-15T12:40:37.044484 #58] ERROR -- : => /opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/encryptor-1.3.0/lib/encryptor.rb:73:in `crypt'
E, [2016-03-15T12:40:37.044515 #58] ERROR -- : => /opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/encryptor-1.3.0/lib/encryptor.rb:44:in `decrypt'
E, [2016-03-15T12:40:37.044546 #58] ERROR -- : => /opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/attr_encrypted-1.4.0/lib/attr_encrypted.rb:197:in `decrypt'
E, [2016-03-15T12:40:37.044577 #58] ERROR -- : => /opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/attr_encrypted-1.4.0/lib/attr_encrypted.rb:280:in `decrypt'
E, [2016-03-15T12:40:37.044617 #58] ERROR -- : => /opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/attr_encrypted-1.4.0/lib/attr_encrypted.rb:143:in `block (2 levels) in attr_encrypted'
E, [2016-03-15T12:40:37.044649 #58] ERROR -- : => /app/app/controllers/api/application_controller.rb:110:in `verify_auth_token'
E, [2016-03-15T12:40:37.044686 #58] ERROR -- : => /opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:432:in `block in make_lambda'
E, [2016-03-15T12:40:37.044718 #58] ERROR -- : => /opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:145:in `call'
E, [2016-03-15T12:40:37.044755 #58] ERROR -- : => /opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:145:in `block in halting_and_conditional'
D, [2016-03-15T12:40:37.044808 #58] DEBUG -- : Exception raised: OpenSSL::Cipher::CipherError: bad decrypt
```

In 2.0.0 there are similar changes to the default behavior, which completely break existing applications

not very elegant

**Comment by saghaulor** [comment]
@tilo There were indeed breaking changes in v2.0.0, hence the major version bump. 

The changes between v1.3.4 and v1.4.0 may have happened because of an unfortunate decision to loosely specify a dependency on Encryptor. Beginning with attr_encrypted v1.3.5+, the dependency on Encryptor was explicitly specified.

Please see https://github.com/attr-encrypted/attr_encrypted/issues/181#issuecomment-171755632 for more info.

Were you able to figure out the problem? I suspect it has something to do with the default algorithm changing in Encryptor v2.0.0. I suspect that when you were using attr_encrypted v1.3.4, it was using encryptor v2.0.0, and when you upgraded attr_encrypted to v1.4.0 it required encryptor v1.3.0. Encryptor < v2.0.0 used `aes-256-cbc` by default, encryptor >= v2.0.0 use `aes-256-gcm` by default.

I apologize for the inconvenience you have experienced.

**Comment by tilo** [comment]
@saghaulor thanks for the explanation! 

Given that there are >1.1 mio downloads for this gem, maybe it would be a good idea to add a note in the post-install hook which explains this when someone innocently tries to install a newer version of the gem :)  It affects a lot of installations..

http://stackoverflow.com/questions/6063725/how-to-use-hooks-in-ruby-gems

**Comment by saghaulor** [comment]
@tilo I fully understand the severity of the situation. It is why I immediately released a version to fix the gem spec mistake.

Unfortunately it didn't occur to me to use a post install hook until I had pushed v2.0.0.
https://github.com/attr-encrypted/attr_encrypted/blob/master/attr_encrypted.gemspec#L58

Unfortunately, I don't believe that hook works when doing a bundle update.

**Comment by tbbooher** [comment]
i upgraded, added the IV field in the db, but still have to use ```, insecure_mode: true, algorithm: 'aes-256-cbc'```

do i need to run a script to re-encrypt everything? If so, I think that would require duplicating the database and then pulling from the old and storing into the new one. It wouldn't be too hard, but would love if there is an easier way.

**Comment by saghaulor** [comment]
@tbbooher There is an example in the readme that hints at how to do re-encryption without having to duplicate the tables etc. https://github.com/attr-encrypted/attr_encrypted#upgrading-from-attr_encrypted-v2x-to-v3x

You could also use a shadow class with the old options to decrypt the object, then pass in the value to your regular class which utilizes the new options.

**Comment by tbbooher** [comment]
@saghaulor -- your readme is helpful, but it runs into the problem of calling an instance method inside the class -- if you implement that is_decrypting the way it is presented, you get:

````method_missing': undefined method `is_decrypting?' for User (call 'User.connection' to establish a connection):Class (NoMethodError)```

Could you explain why you are doing that? The is_decrypting method? Obviously, it will return true if the current action is :decrypting, but why do you want to change the method if it is decrypting?
