### ISSUE TITLE
Upgraded to v2.0.0 and get OpenSSL::Cipher::CipherError

### ISSUE THREAD

**Issue by turgs** [attr-encrypted/attr_encrypted#202]
Hello

Firstly, this issue is likely not a bug with _attr_encrypted_ but rather in what I've done. If anyone can point me in the right direction that'd be great.

I stupidly just upgraded to v2.0.0 doing a blanket `bundle update`. Doing that, I didn't know about attr_encrypted's improvements and hadn't first read the readme. Obviously after upgrading I was getting exception errors as I'd been using the insecure defaults from prior versions.

But now, even after switching to the new defaults and running `rake db:reset`I'm getting `OpenSSL::Cipher::CipherError` exceptions. I assume it's "bad decrypt" but it doesn't actually say explicitly. I cannot figure out what's going on and what I need to fix.

When the model in instantiated, I can assign a value to the encrypted attribute "first name" and retrieve from it no problem. After saving to the database and trying to read it is where I'm having grief.

If there's a better way to do what I'm trying to do with the encryption key, I'd love to know too. Client belongs to a Practice (i.e. business). Practice has many Clients. Practice has many Users too, and any user logged in needs to be able to CRUD (including encrypt/decrypt) Clients.

Here's an example from the Rails console:

    $ rails c
    Running via Spring preloader in process 2263
    Loading development environment (Rails 4.2.6)

    irb(main):001:0> @p = Practice.new(name: 'ABC & Co', timezone: 'Australia/Brisbane')
    => #<Practice id: nil, name: "ABC & Co", salt: nil, created_at: nil, updated_at: nil, deleted_at: nil>

    irb(main):002:0> @p.save!
       (0.6ms)  BEGIN
      SQL (0.9ms)  INSERT INTO "practices" ("name", "salt", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["name", "ABC & Co"], ["salt", "d0100eb97abe2419994d3d3c46f83892f73075de65ec2601982cb80983cc3893f0da86c8626da29749fb2b27da3da612bdf612d05fc7266b254aeee85dbda930"], ["created_at", "2016-03-19 12:33:12.206081"], ["updated_at", "2016-03-19 12:33:12.206081"]]
      Practice Load (1.1ms)  SELECT  "practices".* FROM "practices" WHERE "practices"."id" = $1 LIMIT 1  [["id", 2]]
       (2.4ms)  COMMIT
    => true
    
    irb(main):003:0> @c = Client.new
    => #<Client id: nil, title: nil, encrypted_first_name: nil, encrypted_first_name_iv: nil, encrypted_last_name: nil, encrypted_last_name_iv: nil, encrypted_email: nil, encrypted_email_iv: nil, practice_id: nil, created_at: nil, updated_at: nil, deleted_at: nil>
    
    irb(main):004:0> @c.first_name = 'Steve'
       (2.6ms)  SELECT  "practices"."salt" FROM "practices" WHERE "practices"."id" IS NULL LIMIT 1
    => "Steve"
    
    irb(main):005:0> @c.practice_id = @p.id
    => 2
    
    irb(main):006:0> @c.first_name
    => "Steve"
    
    irb(main):007:0> @c.encrypted_first_name 
    => "OzaSG/96L9hyA1FhWgiTauG4LUTS\n"
    
    irb(main):008:0> @c.encrypted_first_name_iv
    => "1YsL7qtTuVT4vF3q\n"
    
    irb(main):009:0> @c.save!
       (0.3ms)  BEGIN
      Practice Load (0.6ms)  SELECT  "practices".* FROM "practices" WHERE "practices"."id" = $1 LIMIT 1  [["id", 2]]
      SQL (0.9ms)  INSERT INTO "clients" ("encrypted_first_name_iv", "encrypted_first_name", "practice_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["encrypted_first_name_iv", "1YsL7qtTuVT4vF3q\n"], ["encrypted_first_name", "OzaSG/96L9hyA1FhWgiTauG4LUTS\n"], ["practice_id", 2], ["created_at", "2016-03-19 12:34:53.804914"], ["updated_at", "2016-03-19 12:34:53.804914"]]
       (2.4ms)  COMMIT
    => true
    
    irb(main):010:0> @c.id
    => 2
    
    irb(main):011:0> @c.first_name
    => "Steve"
    
    irb(main):012:0> @c2 = Client.find(2)
      Client Load (1.4ms)  SELECT  "clients".* FROM "clients" WHERE "clients"."id" = $1 LIMIT 1  [["id", 2]]
    => #<Client id: 2, title: nil, encrypted_first_name: "OzaSG/96L9hyA1FhWgiTauG4LUTS\n", encrypted_first_name_iv: "1YsL7qtTuVT4vF3q\n", encrypted_last_name: nil, encrypted_last_name_iv: nil, encrypted_email: nil, encrypted_email_iv: nil, practice_id: 2, created_at: "2016-03-19 12:34:53", updated_at: "2016-03-19 12:34:53", deleted_at: nil>
    
    irb(main):013:0> @c2.first_name
       (0.8ms)  SELECT  "practices"."salt" FROM "practices" WHERE "practices"."id" = $1 LIMIT 1  [["id", 2]]
    OpenSSL::Cipher::CipherError: 
      from /Users/tim/.gem/gems/encryptor-2.0.0/lib/encryptor.rb:94:in `final'
      from /Users/tim/.gem/gems/encryptor-2.0.0/lib/encryptor.rb:94:in `crypt'
      from /Users/tim/.gem/gems/encryptor-2.0.0/lib/encryptor.rb:47:in `decrypt'
      from /Users/tim/.gem/gems/attr_encrypted-2.0.0/lib/attr_encrypted.rb:233:in `decrypt'
      from /Users/tim/.gem/gems/attr_encrypted-2.0.0/lib/attr_encrypted.rb:317:in `decrypt'
      from /Users/tim/.gem/gems/attr_encrypted-2.0.0/lib/attr_encrypted.rb:155:in `block (2 levels) in attr_encrypted'
      from (irb):13
      from /Users/tim/.gem/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
      from /Users/tim/.gem/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
      from /Users/tim/.gem/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
      from /Users/tim/.gem/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
      from /Users/tim/.gem/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
      from /Users/tim/.gem/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
      from /Users/tim/.gem/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
      from /Users/tim/.gem/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
      from /Users/tim/.gem/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
    ... 1 levels...
      from /Users/tim/.gem/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
      from /Users/tim/.gem/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
      from /Users/tim/.gem/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
      from /Users/tim/.gem/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
      from /Users/tim/.gem/gems/spring-1.6.4/lib/spring/commands/rails.rb:6:in `call'
      from /Users/tim/.gem/gems/spring-1.6.4/lib/spring/command_wrapper.rb:38:in `call'
      from /Users/tim/.gem/gems/spring-1.6.4/lib/spring/application.rb:185:in `block in serve'
      from /Users/tim/.gem/gems/spring-1.6.4/lib/spring/application.rb:156:in `fork'
      from /Users/tim/.gem/gems/spring-1.6.4/lib/spring/application.rb:156:in `serve'
      from /Users/tim/.gem/gems/spring-1.6.4/lib/spring/application.rb:131:in `block in run'
      from /Users/tim/.gem/gems/spring-1.6.4/lib/spring/application.rb:125:in `loop'
      from /Users/tim/.gem/gems/spring-1.6.4/lib/spring/application.rb:125:in `run'
      from /Users/tim/.gem/gems/spring-1.6.4/lib/spring/application/boot.rb:18:in `<top (required)>'
      from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
      from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
      from -e:1:in `<main>'irb(main):014:0> 

Here's my **Client.rb model**

    class Client < AbstractModel
      attr_encrypted :first_name, key: :encryption_key, charset: 'utf-8'
      ...
    end

**Abstract.rb**

    class AbstractModel < ActiveRecord::Base
      self.abstract_class = true
      def encryption_key
        raise "Must set 'encryption_key'" unless ENV['ATTR_ENCRYPTED_KEY'].present?
        @encryption_key ||= calculate_salt_plus_key(practice_id)
      end
      private
        def calculate_salt_plus_key(practice_id)
          Practice.where(id: practice_id).limit(1).pluck(:salt).first.to_s + ENV['ATTR_ENCRYPTED_KEY']
        end
    end

**Comment by saghaulor** [comment]
@turgs I just attempted to recreate your project. I don't seem to be having any issues with decryption. You'll note I simplified it a bit by utilizing `delegate`. 

```ruby
[2] pry(main)> practice = Practice.create(name: 'CipherError')
   (0.1ms)  begin transaction
  SQL (0.4ms)  INSERT INTO "practices" ("name", "salt", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["name", "CipherError"], ["salt", "e7fe50e5fe25cc248950af3931b48a29e770279ed423018f60109ee6493d21f29b5f42bd3fef76cbf60d1002e2f2ac4c679058d0f316f0b1d03135d468d6e3dc8f54c537133bd6c10adcf1d182810f3708fbbb7940113b50a17d703b3a482ac6f822e5fc008fd89a65b5151e1892ce0bf723a1c77413f3d2bf3ea4bd282a7f2d71e0952cd45ce373032bcc32bc2f7063a6e01d201f2ed8c58eedfe47a4d7ebb1a694564f10b59ff13b98811c92856ef0e99bcafa0996b76b9598e057f19ca5135e5273f3404f664dfd17585d771b7bd867c968bd39b48f52f79562ee65467a4b90e69d829fb9bb8624877369bcfd494d093bcd344d8d12e0b859e51ddb8078"], ["created_at", "2016-03-20 01:57:40.804020"], ["updated_at", "2016-03-20 01:57:40.804020"]]
   (0.8ms)  commit transaction
=> #<Practice:0x007fdefbd3b7d8
 id: 3,
 name: "CipherError",
 salt:
  "e7fe50e5fe25cc248950af3931b48a29e770279ed423018f60109ee6493d21f29b5f42bd3fef76cbf60d1002e2f2ac4c679058d0f316f0b1d03135d468d6e3dc8f54c537133bd6c10adcf1d182810f3708fbbb7940113b50a17d703b3a482ac6f822e5fc008fd89a65b5151e1892ce0bf723a1c77413f3d2bf3ea4bd282a7f2d71e0952cd45ce373032bcc32bc2f7063a6e01d201f2ed8c58eedfe47a4d7ebb1a694564f10b59ff13b98811c92856ef0e99bcafa0996b76b9598e057f19ca5135e5273f3404f664dfd17585d771b7bd867c968bd39b48f52f79562ee65467a4b90e69d829fb9bb8624877369bcfd494d093bcd344d8d12e0b859e51ddb8078",
 created_at: Sun, 20 Mar 2016 01:57:40 UTC +00:00,
 updated_at: Sun, 20 Mar 2016 01:57:40 UTC +00:00>
[3] pry(main)> Client.create(practice: practice, first_name: 'Stephen')
   (0.1ms)  begin transaction
  SQL (0.6ms)  INSERT INTO "clients" ("practice_id", "encrypted_first_name_iv", "encrypted_first_name", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?)  [["practice_id", 3], ["encrypted_first_name_iv", "pIrPuVdHEBxFlRl+\n"], ["encrypted_first_name", "jnWUBJdb1+OThxVH1TwmOFv5qdMZtVg=\n"], ["created_at", "2016-03-20 01:58:23.418182"], ["updated_at", "2016-03-20 01:58:23.418182"]]
   (0.8ms)  commit transaction
=> #<Client:0x007fdefc062358
 id: 3,
 encrypted_first_name: "jnWUBJdb1+OThxVH1TwmOFv5qdMZtVg=\n",
 encrypted_first_name_iv: "pIrPuVdHEBxFlRl+\n",
 practice_id: 3,
 created_at: Sun, 20 Mar 2016 01:58:23 UTC +00:00,
 updated_at: Sun, 20 Mar 2016 01:58:23 UTC +00:00>
[4] pry(main)> Client.last.first_name
  Client Load (0.2ms)  SELECT  "clients".* FROM "clients"  ORDER BY "clients"."id" DESC LIMIT 1
  Practice Load (0.2ms)  SELECT  "practices".* FROM "practices" WHERE "practices"."id" = ? LIMIT 1  [["id", 3]]
=> "Stephen"
```

I hope that this helps.

[bad_decrypt.tar.gz](https://github.com/attr-encrypted/attr_encrypted/files/181129/bad_decrypt.tar.gz)

**Comment by turgs** [comment]
Thanks for looking at it.

Does that suggest the problem I'm having would be someone caused by
something else? I vaguely remember a few years ago when I had a similar
issue that somehow my environments cos contaminated. I could only resolve
the bad decrypt issue by deploying the project to new locations (ie. with a
clean slate).


Tim Burgan

Mobile. 0403 309 564
Email. timburgan@gmail.com

**Comment by turgs** [comment]
I've just run back through this. I don't get an error when I run your code, but I do still get an error when I run mine. As my last comment, I've even moved my project to a new clean environment incase something weird with gems or rails was going on.

I can't see why there'd be an issue in my version that would cause a CipherError.

**Comment by turgs** [comment]
I've narrowed down the issue to a difference between assigning a value to an attribute via:

```
c = Client.new
c.first_name = 'Something'
c.save!
```
vs
```
c = Client.new(first_name: 'Something')
c.save!
```

The later works, the former results in CipherError.

**Comment by saghaulor** [comment]
@turgs I don't see that behavior in the sample project that I uploaded. I think it might be a red herring.

**Comment by turgs** [comment]
I'm not sure what's going on.  I've worked around my issue for now by instantiating the object in the way that doesn't error.

Thanks for your help and time. As a result, I've donated $75 USD to Electronic Frontiers Australia (EFA - similar to the EFF but Australian based) as a thank you.
