### ISSUE TITLE
suggestion: allow user to default to using secret key base as key..

### ISSUE THREAD

**Issue by sblackstone** [attr-encrypted/attr_encrypted#206]
To make this easier to use, it would be cool to allow this construct as a default..

`attr_encrypted :player_password, key: Rails.application.secrets[:secret_key_base][0,32]`

So you could just use an initializer to tell attr_encrypted to "use applications secrets as my AES key" and then you could just reduce everything down to 

`attr_encrypted :player_password`

... I can't think of a reason why using secrets would be bad[tm] but if anyone can think of a reason, I'd love to hear it..

Secret key base is hex, but at 32 digits, you're looking at 340282366920938463463374607431768211456 keys even with the reduced keyspace.

**Comment by grosser** [comment]
can be `Rails.application.secrets.secret_key_base`

**Comment by saghaulor** [comment]
@sblackstone The only reason that I can think as to why it would be bad is that it encourages a sub-optimal pattern in regards to key usage. Ideally, you'll store some metadata about what key was used to encrypt your record, such that in the need of a key rotation, decrypting of old records is possible and encrypting new records with a new key is also possible. 

To that end, while I appreciate your suggestion, I don't think it will be appropriate to add such functionality to the code.
