### ISSUE TITLE
OpenSSL::Cipher::CipherError after upgrade to v3.0

### ISSUE THREAD

**Issue by Ewg777** [attr-encrypted/attr_encrypted#207]
```ruby

OpenSSL::Cipher::CipherError - :
  encryptor (3.0.0) lib/encryptor.rb:98:in `crypt'
  encryptor (3.0.0) lib/encryptor.rb:49:in `decrypt'
  attr_encrypted (3.0.0) lib/attr_encrypted.rb:233:in `decrypt'
  attr_encrypted (3.0.0) lib/attr_encrypted.rb:317:in `decrypt'
  attr_encrypted (3.0.0) lib/attr_encrypted.rb:155:in `block (2 levels) in attr_encrypted'
```
My model
```ruby
  attr_encrypted :country, :key => :encryption_key, :encode => true, :type => :string
```

## wft?!

**Comment by saghaulor** [comment]
@Ewg777 Did you just start using attr_encrypted or did you just recently upgrade?

**Comment by Ewg777** [comment]
@saghaulor just upgraded from v2.0.
Your lib always breaks my app.

**Comment by saghaulor** [comment]
@Ewg777 There were breaking changes between the major releases, hence the major version bumps. You're welcome to use a different lib. Additionally, you're welcome to read the readme. Let me help you: https://github.com/attr-encrypted/attr_encrypted#upgrading-from-attr_encrypted-v2x-to-v3x

**Comment by Ewg777** [comment]
@saghaulor it'll be great to add this to release notes. Thanks

**Comment by ryanj77** [comment]
@saghaulor I've just started a new project with attr_encrypted version 3 and I've received the same error at the very top of this thread.

I'm using this with active record. I had an issue before where it said it needed an IV as well but the issue is a pretty simple fix. Like it says in the notes you need a 256 bit secret key! :-)

Here's an example I found on creating one:

`secret_key = Digest::SHA256.hexdigest('a secret key')`

Perhaps you could add an example in the notes on creating the 256 bit secret key?

**Comment by szymonbaranowski** [comment]
@ryanj77 Im afraid such secret key will cause `ArgumentError: key must be 32 bytes` in the Ruby 2.4

**Comment by gbuchanan-snap** [comment]
Maybe we need to do a little Lunch 'n Learn session here:

[Semantic Versioning](https://semver.org) gives a developer enough context to know when a version bump is probably going to break your app.

**Comment by Ewg777** [comment]
@gbuchanan-snap a version bump shouldn't break the data of the app, should it?

**Comment by gbuchanan-snap** [comment]
It could. You didn't have to upgrade to the new version of the gem if the repercussions of the bump weren't worth addressing. You can lock a version of the gem to a specific major version in your gemfile.
It is not up to the developer of the gem to account for the almost infinite edge cases that invariably arise.

**Comment by mPanasiewicz** [comment]
In my case, the same error when `scret_key_base` was damaged.
