### ISSUE TITLE
Migration from pre-2.0.0 version

### ISSUE THREAD

**Issue by aboutjon** [attr-encrypted/attr_encrypted#208]
I'm running into a bit of an issue updating from our previous version of attr_encrypted.

The steps I'm currently following are:
1. Updated gem to 3.0.0
2. Changed model to use a new key
3. Added migrations to add encrypted_column_name_iv to table

This is where I run into the issue, when I manually run
 `encrypted_data = User.encrypt_column_name("testing", iv: iv, key: key)` 
and save that value over the existing encrypted value with 
`Model.encrypted_column_name = encrypted_data` 
I get the error `ArgumentError: iv must be 12 bytes or longer`.

The iv was generated with `SecureRandom.random_bytes(12)`.

I also tried setting `Model.encrypted_column_name_iv = iv` with the iv being the one used for encryption above but that also results in the same error.

Is there a certain way I should be initializing the iv columns for the migration?

Thanks!

**Comment by saghaulor** [comment]
@aboutjon I don't quite follow what you're trying to accomplish. Are you trying to re-encrypt your data?

**Comment by aboutjon** [comment]
Yep, trying to re-encrypt the existing data. 

In the above example `"testing"` would be the old decrypted value (there's no issue with decryption of the existing data). The issue is after this when trying to save the new encrypted values.

**Comment by saghaulor** [comment]
attr_encrypted should do a lot of this for you if you instantiate the instance of your model. 

```ruby
  user = User.find(id)
  user.column_name = "testing"
  user.save
```

It should handle generating the IV and persisting it.

**Comment by aboutjon** [comment]
Yeah that's what I was thinking (it's the first thing I tried before going the more complicated route) but that also doesn't work.

Right after the migration of the new IV columns and upgrading the gem, I can run

    user = User.find(id)
    user.column_name

I get the error `ArgumentError: must specify an iv` which is okay since I haven't re-encrypted anything yet.

But then I'll run

    user.column_name = "testing"
    user.save

And get the error `ArgumentError: must specify an iv` again

**Comment by aboutjon** [comment]
I found the exact issue. I had a `validates :first_name, :last_name, presence: true` on the model and when I was re-encrypting, I only re-encrypted the first_name. 

It looks like both have to be re-encrypted at the same time otherwise the iv error shows up.
