### ISSUE TITLE
Undefined method encrypted_<attributename>_salt_was

### ISSUE THREAD

**Issue by carter** [attr-encrypted/attr_encrypted#209]
Since upgrading to 3.0.0, I started getting this error. Seems to stem from this call:

https://github.com/attr-encrypted/attr_encrypted/blob/master/lib/attr_encrypted/adapters/active_record.rb#L62

which changed on this commit:

https://github.com/attr-encrypted/attr_encrypted/commit/f9820256c1cd85f89204fd04b90b1c647b94c183

**Comment by saghaulor** [comment]
@carter Thank you for reporting this issue. Can you please provide more info so that we can attempt to codify this problem into a failing test in order to fix it?
