### ISSUE TITLE
AR dirty tracking methods are only defined for the last encrypted attribute

### ISSUE THREAD

**Issue by hoffmanilya** [attr-encrypted/attr_encrypted#218]
When defining multiple attributes to encrypt:

`attr_encrypted :foo, :bar, key: 123`

"dirty" tracking methods are only defined for the last attribute. For example:

`foo_changed? => NoMethodError`
`bar_changed? => false`

Looks like it's happening because of [this](https://github.com/attr-encrypted/attr_encrypted/blob/master/lib/attr_encrypted/adapters/active_record.rb#L53). 

Is this the intended design?

**Comment by duffyjp** [comment]
I have 3 encrypted attributes on a model and they're all responding to ```whatever_changed?```  

Is your NoMethodError something along the lines of:

```ruby
NoMethodError: undefined method `encrypted_bar_changed?'
```
That would imply the encrypted_bar column is not on your model's database.

**Comment by hoffmanilya** [comment]
In my example the underlying `encrypted_foo_changed?` and `encrypted_bar_changed?` both work.

However, if I want to access the attr directly - only `bar_changed?` works.

**Comment by duffyjp** [comment]
Are you allowed to define multiple attributes on the same ```attr_encrypted``` statement?

**Comment by saghaulor** [comment]
@hoffmanilya defining multiple encrypted attributes in one statement is not supported. Please specify each encrypted attribute with it's own statement.
