### ISSUE TITLE
Error: must specify an iv -- with old un-encrypted data

### ISSUE THREAD

**Issue by vandamon** [attr-encrypted/attr_encrypted#224]
I am trying to use attr_encrypted gem version 3.0.3 with a Rails 4.2 application.

I am getting this error ```must specify an iv```  -- with old un-encrypted data. No encrypted data has been added yet.

I have created the fields as described here: https://github.com/attr-encrypted/attr_encrypted#attr_encrypted-with-database-persistence

Am I missing something?

Thanks in advance!

**Comment by jonbcampos** [comment]
+1

**Comment by saghaulor** [comment]
@vandamon How is attr_encrypted supposed to know that your old data is not encrypted? It will attempt to decrypt it. You can conditionally turn off encryption, but you'll need to specify a function that understands what records have been encrypted or not.

**Comment by vandamon** [comment]
> How is attr_encrypted supposed to know that your old data is not encrypted?

Perhaps the gem can provide an option to encrypt existing data. For example, as this one does: https://github.com/jmazzi/crypt_keeper#adding-encryption-to-an-existing-table

However, I found a way to do this. It is a kind of a hack, but it can achieved (after the gem has been setup and fields have been renamed) by storing the data in existing fields safely, then updating their values to nil in DB, and then inserting the original values again. But this time since the gem has been setup, the stored data would be encrypted data.

**Comment by saghaulor** [comment]
@vandamon so at a cursory glance crypt_keeper just provides a helper to encrypt all unencrypted records for you. That's great. However, I don't know everyone's situation, so a solution may be appropriate for one but not for another. 

For instance, say you only have a few thousand existing records, encrypting them all should take a nominal amount of time. At my company, we have tens of millions of records that are encrypted. Trying to encrypt them all in one go without incurring an unacceptable amount of down time is just not possible.
 
This gem has what you need to move forward, you just have to build a migration solution for yourself.

**Comment by vandamon** [comment]
Thanks for the gem Stephen!

**Comment by ibrahim-saifee** [comment]
This might help :) 
https://github.com/attr-encrypted/attr_encrypted/issues/277#issuecomment-606516362
