### ISSUE TITLE
3.0.3 dirty check handling may cause CipherErrors when setting data

### ISSUE THREAD

**Issue by Billiam** [attr-encrypted/attr_encrypted#227]
Just wanted to note that, if using ActiveRecord, and migrating from an older algorithm or encrypt method,  the new (as of 3.0.3) dirty check handling can raise an `OpenSSL::Cipher::CipherError` when *setting* a new encrypted value. 

I understand why that occurs (the setter method now compares the new decrypted value to the old decrypted value) , and that a workaround exists (using `myattr_without_dirtiness=` instead of `myattr=`), but raising a decryption error for **the old value** when changing the field seems like unexpected behavior to me.

As an alternative, could the encrypted values be compared instead of the decrypted values? If not, could the CipherError be rescued in the setter method, and `attribute_will_change!` be assumed in that case?

**Comment by saghaulor** [comment]
@Billiam comparing the cipher text is pointless. Good crypto uses a nonce as the IV, which means the old value and the new value should have a unique IV. Consequently the cipher text will be different, even if the string or key hasn't changed.

You'll have to provide more implementation details or a test case because I don't follow you. We're migrating tons of records in our app using the new code and we're not having any issues. It's possible that I missed something but I suspect it may just be an implementation error.

**Comment by Billiam** [comment]
Understood.

My use case is migrating from the v1.0 attr_encrypted to 3.0.3, having initially used the default encryption mode (single_iv_and_salt) and algorithm (aes-256-cbc).

I have user data encrypted with the old algorithm, and am the process of updating that data on demand using the new attr_encrypted mode and algorithm.

Reading this legacy data using the new algorithm/mode raises a CipherError (I thought this was expected, but please correct me if I'm wrong).

The unexpected part for me was that, when attempting to overwrite this field, there is now an implicit decryption of the *old* data, which then raises the same exception.

Hopefully that makes sense.

**Comment by saghaulor** [comment]
@Billiam here's a way forward if this is still an issue for you. It involves taking advantage of options evaluation at the instance level. https://github.com/attr-encrypted/attr_encrypted#options-are-evaluated

Essentially you'll create a class with functions that switch the options when decrypting and when encrypting. Then you'll cycle through your user records with that class and migrate everything to the new implementation.

You'll also need to add a column for the IV.

```ruby
class MigrateUserCrypto < ActiveRecord::Base
  self.table_name('users')

  attr_encrypted :ssn, mode: mode_toggle(:ssn), algorithm: algorithm_toggle(:ssn), insecure_mode: is_decrypting?(:ssn)

  def is_decrypting?(attribute)
    encrypted_attributes[attribute][:operation] == :decrypting
  end

  def mode_toggle(attribute)
    if is_decrypting?(attribute)
      :single_iv_and_salt
    else
      :per_attribute_iv
    end
  end

  def algorithm_toggle(attribute)
    if is_decrypting?(attribute)
      'aes-256-cbc'
    else
      'aes-256-gcm'
    end
  end
end

MigrateUserCrypto.all.each do |user|
  old_ssn = user.ssn
  user.ssn= old_ssn
  user.save
end
```
