### ISSUE TITLE
Should the IV column be nil, if the value itself is also nil?

### ISSUE THREAD

**Issue by duffyjp** [attr-encrypted/attr_encrypted#228]
Here's a snippit from a record created by factorygirl, with no ssn set:

```ruby
                   :updated_at => Mon, 01 Aug 2016 12:58:16 CDT -05:00,
                :encrypted_ssn => nil,
             :encrypted_ssn_iv => "JtW3rkm/I4jXjODx\n",
                        :email => "jim.lahey.1@example.com",
```

attr_encrypted 3.0.3

Should my encrypted_ssn_iv field be set?  I'm getting some hard to track down ```OpenSSL::Cipher::CipherError:``` errors with no message when dealing with records in this scenario.  My gut feeling tells me the IV should also be nil.

**Comment by saghaulor** [comment]
@duffyjp thanks for reporting this.

This issue duplicates https://github.com/attr-encrypted/attr_encrypted/issues/216

I'm closing this issue and will address the problem in the originally reported issue.

**Comment by saghaulor** [comment]
I took a closer look at this, it's a different issue than #216. As such I'm reopening this issue.
