### ISSUE TITLE
Cannot decrypt after Rails/Gem upgrade

### ISSUE THREAD

**Issue by shakycode** [attr-encrypted/attr_encrypted#230]
We had a legacy Rails 3.0 app with attr_encrypted 1.3.3 and encryptor 1.3.0 and it was working fine.  We've since upgraded to Rails 4.2.6 and are now on attr_encrypted 3.0.3 and encryptor 3.0.0

Writing new credit cards to our model encrypts fine and they will decrypt inline no problem.  However credit cards from legacy data do not decrypt and when read from the rails console return nil.

Here is the settings we have on one of our models (Key is jibberish to protect our codebase)

````
  attr_encrypted :card_number, :key => '6ca41e22-69d2-4d6d-834b-2872d0141032',
                 algorithm: 'aes-256-cbc', mode: :single_iv_and_salt, insecure_mode: true
````

Can anyone provide some guidance on what I may or may not be doing wrong/right here?  I read the docs and have a good understanding of the gem but for some reason legacy data encrypted with the 1.3.3 version will not decrypt and returns nil.

**Comment by saghaulor** [comment]
Can you please demonstrate how you are attempting to decrypt?

Additionally, I hope that isn't your production encryption key.

**Comment by shakycode** [comment]
Sorry about this, but we discovered that legacy data was never being encrypted, it was being stored in plain text so we could not decrypt a plaintext column.  We will be solving this internally with ETL

And no, that is not a production encryption key, I randomized it.

**Comment by shakycode** [comment]
@saghaulor I spoke too soon.  It appears I didn't understand how the gem works.

So basically we have a card_number field that persists CC info to the database.  In legacy app/data (rails 3 and older version of attr_encrypted) we can go to the rails console and do:

````
b = BillingProfile.find(3)
b.card_number # returns 444433332222111
````

In Rails 4.2.6 when we try to do read the card_number attribute


````
b = BillingProfile.find(3)
b.card_number # returns nil
````

**Comment by saghaulor** [comment]
@shakycode I'm not able to reproduce your issue. Admittedly, I didn't completely reproduce the steps stated, as I used a newer version of Rails to create the original record. However, as you can see, I did use an older version of attr_encrypted. The version number is incorrect, apparently I made a mistake when publishing the gem. This is v1.3.4.

```ruby
[8] pry(main)> ActiveRecord::VERSION::STRING
=> "4.2.7.1"
[9] pry(main)> AttrEncrypted::Version.string
=> "1.3.5"
[10] pry(main)> BillingProfile.encrypted_attributes
=> {:card_number=>
  {:prefix=>"encrypted_",
   :suffix=>"",
   :if=>true,
   :unless=>false,
   :encode=>"m",
   :default_encoding=>"m",
   :marshal=>false,
   :marshaler=>Marshal,
   :dump_method=>"dump",
   :load_method=>"load",
   :encryptor=>Encryptor,
   :encrypt_method=>"encrypt",
   :decrypt_method=>"decrypt",
   :mode=>:single_iv_and_salt,
   :key=>"6ca41e22-69d2-4d6d-834b-2872d0141032",
   :attribute=>:encrypted_card_number}}
[11] pry(main)> BillingProfile
=> BillingProfile(id: integer, encrypted_card_number: string, created_at: datetime, updated_at: datetime)
[12] pry(main)> BillingProfile.create(card_number: 'legacy test')
   (0.1ms)  begin transaction
  SQL (1.5ms)  INSERT INTO "billing_profiles" ("encrypted_card_number", "created_at", "updated_at") VALUES (?, ?, ?)  [["encrypted_card_number", "n4BwUmbOChWLmGFTsUxK7w==\n"], ["created_at", "2016-08-23 16:02:49.222181"], ["updated_at", "2016-08-23 16:02:49.222181"]]
   (1.4ms)  commit transaction
=> #<BillingProfile:0x007fbe5eac2b18 id: 3, encrypted_card_number: "n4BwUmbOChWLmGFTsUxK7w==\n", created_at: Tue, 23 Aug 2016 16:02:49 UTC +00:00, updated_at: Tue, 23 Aug 2016 16:02:49 UTC +00:00>
[13] pry(main)> bp = BillingProfile.last
  BillingProfile Load (0.2ms)  SELECT  "billing_profiles".* FROM "billing_profiles"  ORDER BY "billing_profiles"."id" DESC LIMIT 1
=> #<BillingProfile:0x007fbe5b9d8520 id: 3, encrypted_card_number: "n4BwUmbOChWLmGFTsUxK7w==\n", created_at: Tue, 23 Aug 2016 16:02:49 UTC +00:00, updated_at: Tue, 23 Aug 2016 16:02:49 UTC +00:00>
[14] pry(main)> bp.card_number
=> "legacy test"
```

And then I changed to the newest version and decrypted the record without a problem.

```ruby
[1] pry(main)> ActiveRecord::VERSION::STRING
=> "4.2.7.1"
[2] pry(main)> AttrEncrypted::Version.string
=> "3.0.3"
[3] pry(main)> BillingProfile.encrypted_attributes
=> {:card_number=>
  {:prefix=>"encrypted_",
   :suffix=>"",
   :if=>true,
   :unless=>false,
   :encode=>"m",
   :encode_iv=>"m",
   :encode_salt=>"m",
   :default_encoding=>"m",
   :marshal=>false,
   :marshaler=>Marshal,
   :dump_method=>"dump",
   :load_method=>"load",
   :encryptor=>Encryptor,
   :encrypt_method=>"encrypt",
   :decrypt_method=>"decrypt",
   :mode=>:single_iv_and_salt,
   :algorithm=>"aes-256-cbc",
   :key=>"6ca41e22-69d2-4d6d-834b-2872d0141032",
   :insecure_mode=>true,
   :attribute=>:encrypted_card_number}}
[4] pry(main)> bp = BillingProfile.last
  BillingProfile Load (0.2ms)  SELECT  "billing_profiles".* FROM "billing_profiles"  ORDER BY "billing_profiles"."id" DESC LIMIT 1
=> #<BillingProfile:0x007fe310233228 id: 3, encrypted_card_number: "n4BwUmbOChWLmGFTsUxK7w==\n", created_at: Tue, 23 Aug 2016 16:02:49 UTC +00:00, updated_at: Tue, 23 Aug 2016 16:02:49 UTC +00:00>
[5] pry(main)> bp.card_number
=> "legacy test"
[6] pry(main)>
```

I don't believe that there is a problem with the gem. If you're able to pinpoint your issue and prove that it's the gem, please feel free to reopen this issue and include the evidence that you find.
