### ISSUE TITLE
How to use attr_encrypted in postgres json field

### ISSUE THREAD

**Issue by joe11051105** [attr-encrypted/attr_encrypted#232]
thanks.

**Comment by chrisjensen** [comment]
Do you mean to encrypt the entire json as one blob, or to encrypt individual values within the json?
To encrypt the whole json, just set up the field as a text field and set marshal: true as described in the docs [here](https://github.com/attr-encrypted/attr_encrypted#the-marshal-dump_method-and-load_method-options).
To encrypt only certain fields, I created [attr_redactor](https://github.com/chrisjensen/attr_redactor) to help, it's not as full featured as attr_encrypted, but it'll get the job done with basic settings.

**Comment by joe11051105** [comment]
ok, thanks.

**Comment by hkilis** [comment]
Hi @chrisjensen, the field must be set up as **string** type not **text**.. At least it's in the current version I'm not sure if that was working in the version at 2016.
