### ISSUE TITLE
Restricting encrypted attributes from inspect (ActiveRecord)

### ISSUE THREAD

**Issue by jfo84** [attr-encrypted/attr_encrypted#235]
I've had a lot of difficulty trying to stop our logs from including encrypted attribute values as well as the real attribute values.

A monkey patch like [this](https://gist.github.com/jfo84/910bfcdd619ad5a8886fb861807bd3a3) does not work and I'm not exactly sure why.

Has anyone had any success accomplishing this? Clearly somewhere in this library or its dependencies, inspect/as_json has been changed to display the encrypted value instead of the real value, but I couldn't find the implementation.

Thanks!

**Comment by saghaulor** [comment]
@jfo84 I don't understand your issue. Can you please clarify. Perhaps with a contrived example?

**Comment by lichtamberg** [comment]
@jfo84 Mybe you should add them to the application.rb filter?

```ruby
module FlaveAdmin
  class Application < Rails::Application
    ...
    config.filter_parameters += [:password, :iban, :bic]
  end
end
``

**Comment by saghaulor** [comment]
I believe when used correctly, if you're filtering params out as mentioned by @lichtamberg, then the sensitive data should not be appearing in your logs.
