### ISSUE TITLE
key must be 32 bytes

### ISSUE THREAD

**Issue by olegsobchuk** [attr-encrypted/attr_encrypted#258]
After migrate from ruby 2.3.3 to ruby 2.4.0 I've got an exception when I try to fetch my decoded data

```
ArgumentError: key must be 32 bytes
from /home/oleg/.rvm/gems/ruby-2.4.0/gems/encryptor-3.0.0/lib/encryptor.rb:72:in `key='
```

**Comment by saghaulor** [comment]
Hi @olegsobchuk,

I assume that you're having the same problem as documented in https://github.com/attr-encrypted/encryptor/issues/26, namely, your key is more than 32 bytes. Ruby prior to v2.4 used to allow for superfluous length keys. Ruby 2.4 checks to make sure that the key size is the exact size. Try truncating your key to 32 bytes and see if you still have an issue.

**Comment by olegsobchuk** [comment]
@saghaulor I found solution after a little deeper digging...

I use Rails 5.0.2 and in my model I used to `attr_encrypted` as:

`attr_encrypted :password, key: 'this key is generated with rake secret'`

but after some investigating I found that you can use it in 2 ways
1. add `salt` attribute
`attr_encrypted :password, key: 'this key is generated with rake secret', salt: 'super salty'`
2. use for `key` exactly 32 characters 
```
super_key = SecureRandom.base64(32)
attr_encrypted :password, key: super_key
```

**Comment by wmakley** [comment]
I have generated all kinds of different keys using `SecureRandom.base64(32)` and still get this error. Driving me crazy. No the keys aren't null.

**Comment by alex-mohemian** [comment]
@wmakley you need to decode it afterwards.

```key = Base64.encode64(SecureRandom.random_bytes(32))
attr_encrypted :password, key: Base64.decode64(key)```

**Comment by wmakley** [comment]
Thank you, I did eventually figure it out!

**Comment by alex-mohemian** [comment]
@wmakley Glad you figured it out! 😄  I had the same problem today and it took me a while to figure out. Now it's at least documented somewhere if somebody else runs into the same issue.

**Comment by Uysim** [comment]
I rand into the same problem. Any idea to fix it?

**Comment by alex-mohemian** [comment]
@Uysim yes, I explained it 3 posts up. https://github.com/attr-encrypted/attr_encrypted/issues/258#issuecomment-397259672

**Comment by Uysim** [comment]
Ah I see. Nice one @alex-mohemian

**Comment by Uysim** [comment]
How about old data we have? is it still ok?
