### ISSUE TITLE
Deprecation warning with Rails 5.1.0.rc1

### ISSUE THREAD

**Issue by spdawson** [attr-encrypted/attr_encrypted#260]
The following code is in my model class.

```ruby
attr_encrypted :blob
```

When I use the `blob` accessor method, the following appears in the Rails log.

> DEPRECATION WARNING: `blob` is not an attribute known to Active Record. This behavior is deprecated and will be removed in the next version of Rails. If you'd like `blob` to be managed by Active Record, add `attribute :blob` to your class.

As suggested, adding

```ruby
attribute :blob
```

to the model &mdash; immediately before the `attr_encrypted` call &mdash; silences the deprecation warning, and does not appear to impair the operation of the `blob` accessor method.

**Comment by ardavis** [comment]
When I added `attribute :blob` it looks like it shows up in the Rails console. Everything still seems to work as intended, is there a way to tell the attribute that it's overridden?

```
irb(main):001:0> MyObj
=> MyObj(id: integer, encrypted_blob: string, encrypted_blob_iv: string, blob: )
```

**Comment by grosser** [comment]
want to turn this into a PR ? :)

**Comment by codebycliff** [comment]
I'm running into this as well on Rails 5.1.

@grosser What did you have in mind for a pull request? I'm not familiar with the codebase, but my first guess would be to do `class_eval` to define `attribute :xyz` where `:xyz` is the symbol passed to `attr_encrypted`. I'm not sure if that's the right solution or would have any negative side effects. Let me know how I can help.

**Comment by grosser** [comment]
something like https://github.com/attr-encrypted/attr_encrypted/pull/263 ;)

**Comment by codebycliff** [comment]
Perfect. Thank you!

**Comment by avokhmin** [comment]
When will be a new version of gem?

**Comment by danielwestendorf** [comment]
A new gem release to get this included would be 💯.

**Comment by mmahalwy** [comment]
Any update on this?

**Comment by szymonbaranowski** [comment]
Would appreciate a release as well!

**Comment by jasonperrone** [comment]
Those Deprecation warnings are very ugly. When will this make it to master?

**Comment by casperisfine** [comment]
3.1.0 got released yesterday: https://rubygems.org/gems/attr_encrypted/versions/3.1.0
