### ISSUE TITLE
Warning: constant OpenSSL::Cipher::Cipher is deprecated (Ruby 2.4.1)

### ISSUE THREAD

**Issue by bmsatierf** [attr-encrypted/attr_encrypted#264]
Saw this warning while upgrading to Ruby 2.4.1:

```
/Users/bmsatierf/.rvm/gems/ruby-2.4.1@rails/gems/attr_encrypted-1.4.0/lib/attr_encrypted.rb:333: warning: constant OpenSSL::Cipher::Cipher is deprecated
/Users/bmsatierf/.rvm/gems/ruby-2.4.1@rails/gems/encryptor-1.3.0/lib/encryptor.rb:52: warning: constant OpenSSL::Cipher::Cipher is deprecated
```

**Comment by fcarrega** [comment]
Hi,

We are experimenting the same issue with our app.

The syntax of `OpenSSL::Cipher::Cipher.new()` has changed to  ̀OpenSSL::Cipher.new`.

The latest versions of `attr_encrypted` take this change into account, however it seems that you are still using version 1.4.0 of the gem (as we do). Upgrading to a more recent version should solve the problem. Will try on my side and let you know.
