### ISSUE TITLE
How to find a record that is encrypted

### ISSUE THREAD

**Issue by mzaragoza** [attr-encrypted/attr_encrypted#274]
I have set up attr_encrypted in my app with individual 'iv's for every record.

    # Fields
    User.e_name
    User.e_name_iv

I am trying to search the User table for a known name. I've tried:

    User.find_by_name("Joe Bloggs") # undefined method "find_by_name" for Class
    User.where("name = ?", "Joe Bloggs").first # column "name" does not exist
    User.where(:e_name => User.encrypt_name("Joe Bloggs"))  # must specify an iv

How can I find a record by its name?

**Comment by saghaulor** [comment]
@mzaragoza While it is possible to do some searching, it's not very practical. you'll have to potentially iterate through every record trying each respective IV until you have an exact match,  depending on the number of records you have this will not be very practical. 

Have you read the readme? https://github.com/attr-encrypted/attr_encrypted#things-to-consider-before-using-attr_encrypted
