### ISSUE TITLE
Deprecation warning in Rails 5.1.3

### ISSUE THREAD

**Issue by nickurban** [attr-encrypted/attr_encrypted#275]
Using attr_encrypted 3.0.3

This happens when assigning to an `attr_encrypted` attribute:

`DEPRECATION WARNING: <field> is not an attribute known to Active Record. This behavior is deprecated and will be removed in the next version of Rails`

**Comment by srt32** [comment]
Seems like a dup of https://github.com/attr-encrypted/attr_encrypted/issues/260

**Comment by nickurban** [comment]
Looks like you're correct. Thanks.
