### ISSUE TITLE
Can we store the salt in a separate table or database?

### ISSUE THREAD

**Issue by meenakshiBadhan** [attr-encrypted/attr_encrypted#276]
Hi
I’m encrypting some patient health data using attr_encrypted gem. For security purposes, I need to store the salt in a separate table or in a separate database. Is it possible with this gem?
@sbfaulkner @shuber @billymonk

**Comment by saghaulor** [comment]
@meenakshiBadhan fyi, we will be dropping support for salt in a future release.

You could store it in a different table, but you'll need to create your own accessors that contain the logic required to find the given salt.
