### ISSUE TITLE
Is AWS KMS Integration possible?

### ISSUE THREAD

**Issue by lysender** [attr-encrypted/attr_encrypted#279]
Can I use AWS KMS to store my encryption keys?

What I'm planning to do is create a KMS data key and store the encrypted key in a config, then, whenever the plain text key is needed, I just need to call the AWS KMS `Decrypt` API to supply in to `attr_encrypted`.

~~~
class User
  attr_encrypted :email, key: :encryption_key

  def encryption_key
    # Get encryption key from KMS
   decrypt_via_kms(Settings.encrypted_encryption_key)
  end
end
~~~

Has this been done in the past? Also, how can I clear the plain text key stored in memory so it is not stored for too long?

Thanks

**Comment by daveriess** [comment]
Hey @lysender - we are using KMS currently. You may want to consider baking key rotation into your approach so that you can limit the amount of data encrypted with any given data key. This generally will require storing the key cipher-text alongside your encrypted data.

**Comment by lysender** [comment]
@daveriess yeah, I was thinking the same, like store an encrypted DEK (data encryption key) alongside with the encrypted data, however, is it supported by `attr_encrypted`?

It seems pretty straightforward, like I can just wrap ActiveSupport's MessageEncryptor and do what `attr_encrypted` does. I would still prefer if it can be integrated with `attr_encrypted`.

**Comment by ankane** [comment]
Hey @lysender, here's how I integrated the two with KMS data keys: https://github.com/ankane/kms_encrypted

**Comment by lysender** [comment]
@ankane that one looks great! I have gathered enough strategy so far from your input and I think I can do the key rotation by just using the `attr_encrypted` gem.

So I'll just store the encrypted DEK into each as separate field record and let the `key: :encryption_key` decide which key to use, the default key, or the stored key.

**Comment by lysender** [comment]
I'll let you all know if this works on my end.

**Comment by lysender** [comment]
@ankane and @daveriess: we've managed to achieve our encryption strategy with attr_encrypted by using a custom Encryptor which also uses Amazon KMS for key storage.

I have detailed this in a blog post - https://blog.lysender.com/2017/09/rails-encrypting-database-columns-with-key-rotation/

It goes like this:

~~~
encrypted_ssn = 'encryption_method::kek_key_name::encrypted_dek::salt::encrypted_data
~~~

I'm not that experienced with encryption, but here is my default encryption method which is just a wrapper to AES-256-CBC:

~~~
class AesCbcEncryptorService
  class << self
    def name
      'aes_cbc'
    end

    def encrypt(options)
      aes = new_cipher
      aes.encrypt
      aes.key = Digest::SHA256.digest(options[:key])
      aes.iv = options[:salt]

      aes.update(Marshal.dump(options[:value])) << aes.final
    end

    def decrypt(options)
      aes = new_cipher
      aes.decrypt
      aes.key = Digest::SHA256.digest(options[:key])
      aes.iv = options[:salt]

      Marshal.load(aes.update(options[:value]) << aes.final)
    end

    private

    def new_cipher
      OpenSSL::Cipher::Cipher.new('aes-256-cbc')
    end
  end
end
~~~

**Comment by saghaulor** [comment]
@lysender I'm happy to hear that you figured out a solution. In my shop we use KMS as the KEK, to encrypt our DEKs. Our DEKs are stored elsewhere. We have a custom implementation of attr_encrypted where we serialize implementation details similar to how you are doing it. We're also using a custom encryptor class to do the encryption. We've actually moved to an approach where crypto is done outside of our Rails app.

I'm curious, why did you decide to use a hash digest for your key instead of the key itself?

**Comment by saghaulor** [comment]
@ankane Thanks for sharing kms_encrypted. I'll take a look later. You're right, attr_encrypted doesn't handle key management. I'm not sure that it should. But as you pointed out, it's very flexible and works well with complimentary solutions. 

I've thought about trying to open source the solution that we created in my shop, but I'm not sure that I want to wrestle with our legal team.
