### ISSUE TITLE
Check uniqueness of IV when per_attribute_iv mode is used (ensure nonce)

### ISSUE THREAD

**Issue by f3ndot** [attr-encrypted/attr_encrypted#286]
The README makes available [this note](https://github.com/attr-encrypted/attr_encrypted#enforcing-the-iv-as-a-nonce):

> On a related note, most alorithms require that your IV be unique for every record and key combination. You can enforce this using composite unique indexes on your IV and encryption key name/id column. RFC 5084

Instead of imposing this work on the consumer of the Gem, why not make the `attr_encrypted` DSL generate some Rails constraints to ensure a unique IV column? 

e.g.
```ruby
attr_encrypted :recovery_code, key: Rails.application.secrets.some_encryption_key
validates :encrypted_recovery_code_iv, uniqueness: true, allow_nil: true
```

And the migration:

```ruby
 add_index :some_table, :encrypted_recovery_code_iv, unique: true
```

I recognize this is not bulletproof as another column/encrypted attribute using the same key could generate an IV collision. But this is a step in the right direction?

**Comment by saghaulor** [comment]
Thank you for your suggestion, it is good. I would hope that 12 or 16 bytes of entropy is enough to prevent IV collision ([the probability of GCM nonce collision](http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38d.pdf)) especially if you're rotating keys on a regular basis as you should be doing. I wonder if the performance implications are worth the extra safety. Pushing these performance implications on the consumer of this gem seems misplaced. It should be their decision. Moreover, this constraint applies to nonce reuse for a given key. So attr_encrypted would need to know about your key in addition to the nonce. I'm not sure this is appropriate. Hence my reason for keeping it a recommendation.

All that being said, I think attr_encrypted is already doing too much as is. The IV generation should be delegated to the underlying crypto implementation. However, given that it is designed the way it is, I don't think we can change things now. I've considered a simpler approach but I think it would required authoring an entirely new set of libraries as the changes would be quite extreme.
