### ISSUE TITLE
Rails is trying to save the non-encrypted attribute to the database

### ISSUE THREAD

**Issue by mauro-oto** [attr-encrypted/attr_encrypted#290]
Hi, thanks for your work on this gem!

I came across many Rails 5.1 deprecation warnings using the latest release (3.0.3), so I tried using the latest master commit (https://github.com/attr-encrypted/attr_encrypted/commit/e19445a9ae38ed9a55608d28a80e32126f30efd1), which includes the merged but unreleased PR https://github.com/attr-encrypted/attr_encrypted/pull/263. However, using this fix breaks functionality on my app: 

```
ActiveRecord::StatementInvalid:
  Mysql2::Error: Unknown column 'date_of_birth' in 'field list': INSERT INTO `people` (`first_name`, `last_name`, `encrypted_date_of_birth`, `created_at`, `updated_at`, `date_of_birth`) VALUES ('John', 'Doe', '57ud48vFk8t+/8SVjtGYpg==\n', '2017-12-29 20:32:54', '2017-12-29 20:32:54', NULL)
```

After the attribute `date_of_birth` is added via `attr_encrypted :date_of_birth` and in turn by `attribute attr`, the attribute gets used for the `INSERT` statement, and execution fails because it's not an actual db column. 

By adding `attr_readonly :date_of_birth`, I can make it work for the most part, since it skips saving to the db, but then some things like `update_attribute` are still broken. 

Thanks for any help!

**Comment by benlangfeld** [comment]
It appears this might be solved by an upgrade from Rails 5.1.4 to 5.1.6.

**Comment by saghaulor** [comment]
@mauro-oto did upgrading to Rails 5.1.6 fix your problem?

**Comment by benlangfeld** [comment]
Yes. Mauro was working on my project at the time he filed this. We have since upgraded and no longer have the problem. This can be closed.
