### ISSUE TITLE
Unable to find record with where query in version 3.0.0

### ISSUE THREAD

**Issue by nkchouhan** [attr-encrypted/attr_encrypted#296]
Hi,

I am unable to find out records with where query. I'm used attr_encrypted (3.0.3) in rails Rails 4.2.6. I'm trying with encrypted value but encrypted values are all time change. please help me.

Thanks

**Comment by timkrins** [comment]
From the project README:

> While choosing to encrypt at the attribute level is the most secure solution, it is not without drawbacks. Namely, you cannot search the encrypted data, and because you can't search it, you can't index it either.

You will need to determine another way to search through your records - which all depends on why you are trying to search an encrypted column in the first place.
