### ISSUE TITLE
missing_attribute: encrypted_p256dh

### ISSUE THREAD

**Issue by admin-it** [attr-encrypted/attr_encrypted#317]
I've been using this gem for a while and today I was updating some code in a controller and called the to_json method on a collection and got the error missing_attribute: encrypted_p256dh. 

Here is my code:

     @users = User.select("id, email, first_name, last_name, lng, lat").to_json

I've looked around but cannot find anyone else with this issue. 

BTW, none of the columns in the select are encrypted.

**Comment by an-ju** [comment]
I had a similar issue.  I resolved it by adding the `only` option to `to_json`.

So this may solve your problem
`@users = User.select("id, email, first_name, last_name, lng, lat").to_json(only: %I[id, email, first_name, last_name, lng, lat])`
