### ISSUE TITLE
encryption gives different results

### ISSUE THREAD

**Issue by robertosante** [attr-encrypted/attr_encrypted#319]
hello guys when i encrypt any of my attributes example: 

```
class MyClassEncrypted < MyClass
  attr_encrypted :account_number,  key: 'my_key_secret_etc ', iv: 'my_iv_secret_etc'
end
```
if i create a record using MyClassEncrypted.new i get a different account_number encrypted result than if I do

`MyClassEncrypted.encrypt_account_number('123',  key: 'my_key_secret_etc ', iv: 'my_iv_secret_etc')`

anybody knows why? im trying to decrypt accounts given the encrypted_account_number but it seems a different iv is set for every record even though i declared the same iv. Any help will be appreciated

**Comment by saghaulor** [comment]
@robertosante You should be using a different IV per record, this is specified in the [AES GCM RFC. ](https://tools.ietf.org/html/rfc5288#section-3) Therefore, attr_encrypted generates a unique IV per record. You cannot pass in a class level IV.
