### ISSUE TITLE
attr_encrypted is completely unsafe

### ISSUE THREAD

**Issue by danpal** [attr-encrypted/attr_encrypted#32]
You are using cbc mode with the same :iv over an over.
see this discussion:
https://github.com/danpal/encryptor/commit/c1b7e39538cb841a809053a7936b610e92a4bde0

This gem is quite downloaded(36,520 total downloads). It should be fixed, and users should at least be warned.

**Comment by mhuggins** [comment]
Apologies for my naivety, but is it safe to store the `salt` value on the same record as the encrypted data, per the [sample code](https://github.com/attr-encrypted/attr_encrypted/commit/3f7de296d285f99b84ec227e7882ca4795d2cff5#diff-9310b60e834f16e483f841518df994f8R42) that @brianlucas linked to?

    class User < ActiveRecord::Base
      attr_encrypted :ssn,
          mode: :per_attribute_iv_and_salt,
          key: ->(record) { Encryptor.encrypt(value: record.salt, key: KEY) }

      after_initialize :assign_salt

      def assign_salt
        self.salt ||= Digest::SHA256.hexdigest((Time.now.to_i * rand(1000)).to_s)[0..15]
      end
    end

**Comment by jjasonclark** [comment]
Yes, it is safe for the salt. It doesn't even need to be secret.  https://en.wikipedia.org/wiki/Salt_(cryptography)
