### ISSUE TITLE
Last attribute in ecnrypted list gets 'leaked'

### ISSUE THREAD

**Issue by jantequera** [attr-encrypted/attr_encrypted#326]
Rails 5.1.6
Ruby 2.5.1
Gem version: 3.1.0

```rb
# On a Test model
attr_encrypted :field_1, :field_2, :field_3, key: :my_encryption_method
```

```rb
# On the rails console
> Test.select(:id).first
#<Test:0x00007fcf6346da68> {
  "id" => 1,
  "field_3" => nil
}
```

Try swapping fields in the attr_encrypted declaration, and then it is `field_2` the one added to the object with selected fields. Leave just one field encrypted (`field_1`, fore example), and it is added when running that same command.

Basically: _the last attribute in the list of attributes passed to `attr_encrypted` gets 'leaked'_

Curiously enough, though:

```rb
> Test.select(:id).first.field_3
# SQL query blabla
ActiveModel::MissingAttributeError: missing attribute: encrypted_field_3
from /Users/julio/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/attribute_methods/read.rb:71:in `block in _read_attribute'
```

Which is obvious because i didn't select the encrypted version of the field, but might be worth adding

I'm inclined to think this is not intended. Why does this happen and how can we fix it?

**Comment by saghaulor** [comment]
The way attr_encrypted is written, this single line macro for multiple encrypted attributes is not supported. Please use a separate macro and options for each encrypted attribute.

**Comment by jantequera** [comment]
Thanks for your reply! 

So now I'm trying to do this:

```rb
# On a Test model
attr_encrypted :field_1, key: :my_encryption_method
attr_encrypted :field_2, key: :my_encryption_method
attr_encrypted :field_3, key: :my_encryption_method
```

```rb
# On the rails console
> Test.select(:id).first
#<Test:0x00007fcf6346da68> {
  "id" => 1,
  "field_1" => nil,
  "field_2" => nil,
  "field_3" => nil
}
```
Did I miss something on your reply?

I've also tried declaring the fields without custom key and the same happens.

I'm willing to help to solve this and submit a PR if you have any pointers :)
