### ISSUE TITLE
ActionText support

### ISSUE THREAD

**Issue by phildionne** [attr-encrypted/attr_encrypted#342]
Hi there,

Rails 6 is not out yet, but I've been trying encrypt `ActionText::RichText` contents with no success until now. I'm wondering if someone has an idea of how to get it working.

The action happens in:
- https://github.com/rails/rails/blob/master/actiontext/app/models/action_text/rich_text.rb
- https://github.com/rails/rails/blob/master/actiontext/lib/action_text/serialization.rb

I think the key problem is an incompatibility between `attr_encrypted` and `serialize`.

```ruby
class RichText < ActiveRecord::Base
    # ...
    serialize :body, ActionText::Content

    # What would be great
    attr_encrypted :body, key: "some-key
end
```

Before attempting any of this, make sure to update your schema:

```ruby
create_table "action_text_rich_texts", force: :cascade do |t|
    # ...
    t.text "encrypted_body"
    t.string "encrypted_body_iv"
end
```

**Comment by jvanus** [comment]
@phildionne Did you find a way to make attr_encrypted work with ActionText?

**Comment by phildionne** [comment]
I didn’t, and switched to Https://github.com/ankane/lockbox to make it work.
