### ISSUE TITLE
Release 3.2 with ActionSupport.on_load

### ISSUE THREAD

**Issue by typeoneerror** [attr-encrypted/attr_encrypted#389]
I realize that maintenance is in flux (https://github.com/attr-encrypted/attr_encrypted/issues/379), but I'm wondering if someone might be able to cut a 3.2 release to fix compatibility with Rails 5.2?

Specifically, it'd be great if https://github.com/attr-encrypted/attr_encrypted/commit/3ea0c45eacca2077b473359caef0df405733a19d could be released.

Happy to help if I can.

**Comment by joshbranham** [comment]
This was released in 4.0
