### ISSUE TITLE
Keyword args update needed for Ruby 3

### ISSUE THREAD

**Issue by jfouse** [attr-encrypted/attr_encrypted#398]
One example I've hit is here, though there may be others:
https://github.com/attr-encrypted/attr_encrypted/blob/a96693e9a2a25f4f910bf915e29b0f364f277032/lib/attr_encrypted/adapters/active_record.rb#L65

needs to be:
`attribute_changed?(attr, **options)`

That would be an easy PR, I just don't know at a glance if there are other examples

**Comment by joshbranham** [comment]
Resolved in https://github.com/attr-encrypted/attr_encrypted/pull/383
