### ISSUE TITLE
Create a new release to support newer Ruby versions

### ISSUE THREAD

**Issue by markclong** [attr-encrypted/attr_encrypted#454]
We're attempting to upgrade to Ruby 3.2 and found that we need a version of `attr_encrypted` that has DataMapper removed (https://github.com/attr-encrypted/attr_encrypted/pull/439) for compatibility. We could reference the commit or fork this, but we would prefer an official release. Could you release a point version that includes the recent changes? 

@joshbranham @mvastola

**Comment by joshbranham** [comment]
All set @markclong 👍

**Comment by markclong** [comment]
Incredible, thank you.
