### ISSUE TITLE
Defined methods in an anonymous module

### ISSUE THREAD

**Issue by tpickett66** [attr-encrypted/attr_encrypted#99]
Would the maintainers be open to a pull request moving the generated methods to either an anonymous or usefully named module similar to `state_machine`. This would allow for end users to more easily manipulate the execution path on these methods. In my particular instance I'd like to be able to rescue from errors raised in the decryption process and handle them in an application specific manner.

With the current implementation we would have to do something like:

```ruby
class User
  attr_encrypted :email

  def email_rescuing_errors
    email_raising_errors
  rescue AttrEncrypted::Errors::Error
    self.email = nil
  end
  alias_method :email_raising_errors, :email
  alias_method :email, :email_rescuing_errors
end
```

But with a module inserted in the inheritance chain we could simplify things quite a bit:
```ruby
class User
  attr_encrypted :email

  def email
    super
  rescue AttrEncrypted::Errors::Error
    self.email = nil
  end
end
```

Additionally I suspect it could simplify the implementation of custom (en|de)cryptors.

**Comment by saghaulor** [comment]
@tpickett66 this is a nice suggestion. It's already possible to do this with `Module.prepend`.

```ruby
class Cog < ActiveRecord::Base
   attr_encrypted :name, key: encryption_key
end

module WithRescuing
  def name=(value)
    puts "Prepended"
    super(value)
  end
end

Cog.prepend WithRescuing
cog = Cog.new
cog.name= 'derp'
Prepended
=> "derp"

=> #<Cog:0x007fcd4e8a9a08
 id: nil,
 encrypted_name: "NNIprnTquRFOfhuDNUWgIXR/gSQ=\n",
 encrypted_name_iv: "jkydnySBCPwZCuSt\n",
 teeth: nil,
 encrypted_nickname: nil,
 encrypted_nickname_iv: nil,
 created_at: nil,
 updated_at: nil>
```
